//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dp_CfgValueDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dp_CfgValueDef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTvalue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dp_CfgValueDef", propOrder = {
    "ucpTindex",
    "ucpTname",
    "ucpTvalue"
})
public class DpCfgValueDef {

    @XmlElement(name = "UCPTindex")
    protected Integer ucpTindex;
    @XmlElement(name = "UCPTname", required = true)
    protected String ucpTname;
    @XmlElement(name = "UCPTvalue", required = true)
    protected ELonString ucpTvalue;

    /**
     * Gets the value of the ucpTindex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTindex() {
        return ucpTindex;
    }

    /**
     * Sets the value of the ucpTindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTindex(Integer value) {
        this.ucpTindex = value;
    }

    /**
     * Gets the value of the ucpTname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTname() {
        return ucpTname;
    }

    /**
     * Sets the value of the ucpTname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTname(String value) {
        this.ucpTname = value;
    }

    /**
     * Gets the value of the ucpTvalue property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTvalue() {
        return ucpTvalue;
    }

    /**
     * Sets the value of the ucpTvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTvalue(ELonString value) {
        this.ucpTvalue = value;
    }

}
