//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized data point data type.
 * 					Example:  xSelect="//Item[@xsi:type="Dp_Data"][starts-with(UCPTname,'Net/')]"
 * 			
 * 
 * <p>Java class for Dp_Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dp_Data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTvalue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="UCPTpointStatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTpriority" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Priority" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmaxAge" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="UCPTpropagate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmetaDataPath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dp_Data", propOrder = {
    "ucpTvalue",
    "ucpTpointStatus",
    "ucpTpriority",
    "ucpTmaxAge",
    "ucpTpropagate",
    "ucpTmetaDataPath"
})
@XmlSeeAlso({
    UFPTalarmNotifierData.class,
    UFPTdataLoggerData.class,
    UFPTschedulerData.class
})
public class DpData
    extends ItemData
{

    @XmlElement(name = "UCPTvalue")
    protected List<ELonString> ucpTvalue;
    @XmlElement(name = "UCPTpointStatus")
    protected ELonString ucpTpointStatus;
    @XmlElement(name = "UCPTpriority")
    protected Integer ucpTpriority;
    @XmlElement(name = "UCPTmaxAge")
    protected Float ucpTmaxAge;
    @XmlElement(name = "UCPTpropagate")
    protected Short ucpTpropagate;
    @XmlElement(name = "UCPTmetaDataPath")
    protected EPath ucpTmetaDataPath;

    /**
     * Gets the value of the ucpTvalue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ucpTvalue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUCPTvalue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ELonString }
     * 
     * 
     */
    public List<ELonString> getUCPTvalue() {
        if (ucpTvalue == null) {
            ucpTvalue = new ArrayList<ELonString>();
        }
        return this.ucpTvalue;
    }

    /**
     * Gets the value of the ucpTpointStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTpointStatus() {
        return ucpTpointStatus;
    }

    /**
     * Sets the value of the ucpTpointStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTpointStatus(ELonString value) {
        this.ucpTpointStatus = value;
    }

    /**
     * Gets the value of the ucpTpriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTpriority() {
        return ucpTpriority;
    }

    /**
     * Sets the value of the ucpTpriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTpriority(Integer value) {
        this.ucpTpriority = value;
    }

    /**
     * Gets the value of the ucpTmaxAge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getUCPTmaxAge() {
        return ucpTmaxAge;
    }

    /**
     * Sets the value of the ucpTmaxAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setUCPTmaxAge(Float value) {
        this.ucpTmaxAge = value;
    }

    /**
     * Gets the value of the ucpTpropagate property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUCPTpropagate() {
        return ucpTpropagate;
    }

    /**
     * Sets the value of the ucpTpropagate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUCPTpropagate(Short value) {
        this.ucpTpropagate = value;
    }

    /**
     * Gets the value of the ucpTmetaDataPath property.
     * 
     * @return
     *     possible object is
     *     {@link EPath }
     *     
     */
    public EPath getUCPTmetaDataPath() {
        return ucpTmetaDataPath;
    }

    /**
     * Sets the value of the ucpTmetaDataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPath }
     *     
     */
    public void setUCPTmetaDataPath(EPath value) {
        this.ucpTmetaDataPath = value;
    }

}
