//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Resets a Dp's priority (called with 'InvokeCmd' operation)
 * 			
 * 
 * <p>Java class for Dp_ResetPrio_Invoke complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dp_ResetPrio_Invoke"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTpriority" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Priority" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dp_ResetPrio_Invoke", propOrder = {
    "ucpTpriority"
})
public class DpResetPrioInvoke
    extends Item
{

    @XmlElement(name = "UCPTpriority")
    protected Integer ucpTpriority;

    /**
     * Gets the value of the ucpTpriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTpriority() {
        return ucpTpriority;
    }

    /**
     * Sets the value of the ucpTpriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTpriority(Integer value) {
        this.ucpTpriority = value;
    }

}
