//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DpRef_eDiscriminator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DpRef_eDiscriminator"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="dir_in"/&gt;
 *     &lt;enumeration value="dir_out"/&gt;
 *     &lt;enumeration value="dir_in_out"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DpRef_eDiscriminator")
@XmlEnum
public enum DpRefEDiscriminator {

    @XmlEnumValue("dir_in")
    DIR_IN("dir_in"),
    @XmlEnumValue("dir_out")
    DIR_OUT("dir_out"),
    @XmlEnumValue("dir_in_out")
    DIR_IN_OUT("dir_in_out");
    private final String value;

    DpRefEDiscriminator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DpRefEDiscriminator fromValue(String v) {
        for (DpRefEDiscriminator c: DpRefEDiscriminator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
