//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for E_Dummy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="E_Dummy"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DummyA" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Dp_eType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "E_Dummy", propOrder = {
    "dummyA"
})
public abstract class EDummy
    extends Item
{

    @XmlElement(name = "DummyA", required = true)
    @XmlSchemaType(name = "string")
    protected DpEType dummyA;

    /**
     * Gets the value of the dummyA property.
     * 
     * @return
     *     possible object is
     *     {@link DpEType }
     *     
     */
    public DpEType getDummyA() {
        return dummyA;
    }

    /**
     * Sets the value of the dummyA property.
     * 
     * @param value
     *     allowed object is
     *     {@link DpEType }
     *     
     */
    public void setDummyA(DpEType value) {
        this.dummyA = value;
    }

}
