//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized functional block configuration type. It contains an array of 'E_DpRef'.
 * 					Example:  xSelect="//Item[@xsi:type="Fb_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="Fb_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for Fb_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fb_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DataPoint" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_DpRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fb_Cfg", propOrder = {
    "dataPoint"
})
@XmlSeeAlso({
    FPMCfg.class,
    UFPTanalogFunctionBlockCfg.class,
    UFPTalarmGeneratorCfg.class,
    UFPTalarmNotifierCfg.class,
    UFPTcalendarCfg.class,
    UFPTdataLoggerCfg.class,
    UFPTdigitalInputCfg.class,
    UFPTdigitalOutputCfg.class,
    UFPTnodeObjectCfg.class,
    UFPTpulseCounterCfg.class,
    UFPTrealTimeClockCfg.class,
    UFPTschedulerCfg.class,
    UFPTtypeTranslatorCfg.class,
    LONFbCfg.class,
    VirtualFbCfg.class,
    MODFbCfg.class,
    MBSFbCfg.class
})
public class FbCfg
    extends ItemCfg
{

    @XmlElement(name = "DataPoint")
    protected List<EDpRef> dataPoint;

    /**
     * Gets the value of the dataPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EDpRef }
     * 
     * 
     */
    public List<EDpRef> getDataPoint() {
        if (dataPoint == null) {
            dataPoint = new ArrayList<EDpRef>();
        }
        return this.dataPoint;
    }

}
