//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Service data type of the service 'FileSystem'.
 * 					Example:  xSelect="//Item[@xsi:type="FileSystem_Data"][UCPTname="/root/alarmLog/histlog0.csv"][UCPTfileFormat="text"]"
 * 			
 * 
 * <p>Java class for FileSystem_Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileSystem_Data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTfileFormat" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTfileSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileSystem_Data", propOrder = {
    "ucpTfileFormat",
    "ucpTfileSize",
    "value"
})
public class FileSystemData
    extends ItemData
{

    @XmlElement(name = "UCPTfileFormat", required = true)
    protected ELonString ucpTfileFormat;
    @XmlElement(name = "UCPTfileSize")
    protected Integer ucpTfileSize;
    @XmlElement(name = "Value", required = true)
    protected String value;

    /**
     * Gets the value of the ucpTfileFormat property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTfileFormat() {
        return ucpTfileFormat;
    }

    /**
     * Sets the value of the ucpTfileFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTfileFormat(ELonString value) {
        this.ucpTfileFormat = value;
    }

    /**
     * Gets the value of the ucpTfileSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTfileSize() {
        return ucpTfileSize;
    }

    /**
     * Sets the value of the ucpTfileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTfileSize(Integer value) {
        this.ucpTfileSize = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
