//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FPM_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPM_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;attribute name="fpmType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPM_Cfg")
public class FPMCfg
    extends FbCfg
{

    @XmlAttribute(name = "fpmType", required = true)
    protected String fpmType;

    /**
     * Gets the value of the fpmType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpmType() {
        return fpmType;
    }

    /**
     * Sets the value of the fpmType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpmType(String value) {
        this.fpmType = value;
    }

}
