//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			  Response to LON specific device command 'PowerlineData'.
 * 			
 * 
 * <p>Java class for LON_Device_PowerlineData_InvokeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Device_PowerlineData_InvokeResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FrequencyInfo" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_DataFrequencyInfo" maxOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Device_PowerlineData_InvokeResponse", propOrder = {
    "frequencyInfo"
})
public class LONDevicePowerlineDataInvokeResponse
    extends ItemData
{

    @XmlElement(name = "FrequencyInfo", required = true)
    protected List<LONDeviceDataFrequencyInfo> frequencyInfo;

    /**
     * Gets the value of the frequencyInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frequencyInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrequencyInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONDeviceDataFrequencyInfo }
     * 
     * 
     */
    public List<LONDeviceDataFrequencyInfo> getFrequencyInfo() {
        if (frequencyInfo == null) {
            frequencyInfo = new ArrayList<LONDeviceDataFrequencyInfo>();
        }
        return this.frequencyInfo;
    }

}
