//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			  Response to LON specific device command 'RepeatingData'.
 * 			
 * 
 * <p>Java class for LON_Device_RepeatingData_InvokeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Device_RepeatingData_InvokeResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTplrCommissionStatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTplrOnlineStatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTcommAttempts" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTcommFailures" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTcommAgentSwitch" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTcommSkipped" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTfailureHistory" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTproxyAgentCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPThopCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RepeatChain" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FrequencyInfo" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_DataFrequencyInfo"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Device_RepeatingData_InvokeResponse", propOrder = {
    "ucpTplrCommissionStatus",
    "ucpTplrOnlineStatus",
    "ucpTcommAttempts",
    "ucpTcommFailures",
    "ucpTcommAgentSwitch",
    "ucpTcommSkipped",
    "ucpTfailureHistory",
    "ucpTproxyAgentCount",
    "ucpThopCount",
    "repeatChain"
})
public class LONDeviceRepeatingDataInvokeResponse
    extends ItemData
{

    @XmlElement(name = "UCPTplrCommissionStatus", required = true)
    protected ELonString ucpTplrCommissionStatus;
    @XmlElement(name = "UCPTplrOnlineStatus", required = true)
    protected ELonString ucpTplrOnlineStatus;
    @XmlElement(name = "UCPTcommAttempts")
    protected int ucpTcommAttempts;
    @XmlElement(name = "UCPTcommFailures")
    protected int ucpTcommFailures;
    @XmlElement(name = "UCPTcommAgentSwitch")
    protected int ucpTcommAgentSwitch;
    @XmlElement(name = "UCPTcommSkipped")
    protected int ucpTcommSkipped;
    @XmlElement(name = "UCPTfailureHistory", required = true)
    protected ELonString ucpTfailureHistory;
    @XmlElement(name = "UCPTproxyAgentCount")
    protected int ucpTproxyAgentCount;
    @XmlElement(name = "UCPThopCount")
    protected int ucpThopCount;
    @XmlElement(name = "RepeatChain")
    protected List<LONDeviceRepeatingDataInvokeResponse.RepeatChain> repeatChain;

    /**
     * Gets the value of the ucpTplrCommissionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTplrCommissionStatus() {
        return ucpTplrCommissionStatus;
    }

    /**
     * Sets the value of the ucpTplrCommissionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTplrCommissionStatus(ELonString value) {
        this.ucpTplrCommissionStatus = value;
    }

    /**
     * Gets the value of the ucpTplrOnlineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTplrOnlineStatus() {
        return ucpTplrOnlineStatus;
    }

    /**
     * Sets the value of the ucpTplrOnlineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTplrOnlineStatus(ELonString value) {
        this.ucpTplrOnlineStatus = value;
    }

    /**
     * Gets the value of the ucpTcommAttempts property.
     * 
     */
    public int getUCPTcommAttempts() {
        return ucpTcommAttempts;
    }

    /**
     * Sets the value of the ucpTcommAttempts property.
     * 
     */
    public void setUCPTcommAttempts(int value) {
        this.ucpTcommAttempts = value;
    }

    /**
     * Gets the value of the ucpTcommFailures property.
     * 
     */
    public int getUCPTcommFailures() {
        return ucpTcommFailures;
    }

    /**
     * Sets the value of the ucpTcommFailures property.
     * 
     */
    public void setUCPTcommFailures(int value) {
        this.ucpTcommFailures = value;
    }

    /**
     * Gets the value of the ucpTcommAgentSwitch property.
     * 
     */
    public int getUCPTcommAgentSwitch() {
        return ucpTcommAgentSwitch;
    }

    /**
     * Sets the value of the ucpTcommAgentSwitch property.
     * 
     */
    public void setUCPTcommAgentSwitch(int value) {
        this.ucpTcommAgentSwitch = value;
    }

    /**
     * Gets the value of the ucpTcommSkipped property.
     * 
     */
    public int getUCPTcommSkipped() {
        return ucpTcommSkipped;
    }

    /**
     * Sets the value of the ucpTcommSkipped property.
     * 
     */
    public void setUCPTcommSkipped(int value) {
        this.ucpTcommSkipped = value;
    }

    /**
     * Gets the value of the ucpTfailureHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTfailureHistory() {
        return ucpTfailureHistory;
    }

    /**
     * Sets the value of the ucpTfailureHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTfailureHistory(ELonString value) {
        this.ucpTfailureHistory = value;
    }

    /**
     * Gets the value of the ucpTproxyAgentCount property.
     * 
     */
    public int getUCPTproxyAgentCount() {
        return ucpTproxyAgentCount;
    }

    /**
     * Sets the value of the ucpTproxyAgentCount property.
     * 
     */
    public void setUCPTproxyAgentCount(int value) {
        this.ucpTproxyAgentCount = value;
    }

    /**
     * Gets the value of the ucpThopCount property.
     * 
     */
    public int getUCPThopCount() {
        return ucpThopCount;
    }

    /**
     * Sets the value of the ucpThopCount property.
     * 
     */
    public void setUCPThopCount(int value) {
        this.ucpThopCount = value;
    }

    /**
     * Gets the value of the repeatChain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repeatChain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepeatChain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONDeviceRepeatingDataInvokeResponse.RepeatChain }
     * 
     * 
     */
    public List<LONDeviceRepeatingDataInvokeResponse.RepeatChain> getRepeatChain() {
        if (repeatChain == null) {
            repeatChain = new ArrayList<LONDeviceRepeatingDataInvokeResponse.RepeatChain>();
        }
        return this.repeatChain;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FrequencyInfo" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_DataFrequencyInfo"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTname",
        "frequencyInfo"
    })
    public static class RepeatChain {

        @XmlElement(name = "UCPTname", required = true)
        protected String ucpTname;
        @XmlElement(name = "FrequencyInfo", required = true)
        protected LONDeviceDataFrequencyInfo frequencyInfo;

        /**
         * Gets the value of the ucpTname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTname() {
            return ucpTname;
        }

        /**
         * Sets the value of the ucpTname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTname(String value) {
            this.ucpTname = value;
        }

        /**
         * Gets the value of the frequencyInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LONDeviceDataFrequencyInfo }
         *     
         */
        public LONDeviceDataFrequencyInfo getFrequencyInfo() {
            return frequencyInfo;
        }

        /**
         * Sets the value of the frequencyInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LONDeviceDataFrequencyInfo }
         *     
         */
        public void setFrequencyInfo(LONDeviceDataFrequencyInfo value) {
            this.frequencyInfo = value;
        }

    }

}
