//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LON_Device_DataFrequencyInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Device_DataFrequencyInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTfrequency" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTsignalMeasurementType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTsignalStrength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTsignalMargin" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTsignalUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Device_DataFrequencyInfo", propOrder = {
    "ucpTfrequency",
    "ucpTsignalMeasurementType",
    "ucpTsignalStrength",
    "ucpTsignalMargin",
    "ucpTsignalUnit"
})
public class LONDeviceDataFrequencyInfo {

    @XmlElement(name = "UCPTfrequency")
    protected int ucpTfrequency;
    @XmlElement(name = "UCPTsignalMeasurementType", required = true)
    protected ELonString ucpTsignalMeasurementType;
    @XmlElement(name = "UCPTsignalStrength")
    protected int ucpTsignalStrength;
    @XmlElement(name = "UCPTsignalMargin")
    protected int ucpTsignalMargin;
    @XmlElement(name = "UCPTsignalUnit")
    protected String ucpTsignalUnit;

    /**
     * Gets the value of the ucpTfrequency property.
     * 
     */
    public int getUCPTfrequency() {
        return ucpTfrequency;
    }

    /**
     * Sets the value of the ucpTfrequency property.
     * 
     */
    public void setUCPTfrequency(int value) {
        this.ucpTfrequency = value;
    }

    /**
     * Gets the value of the ucpTsignalMeasurementType property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTsignalMeasurementType() {
        return ucpTsignalMeasurementType;
    }

    /**
     * Sets the value of the ucpTsignalMeasurementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTsignalMeasurementType(ELonString value) {
        this.ucpTsignalMeasurementType = value;
    }

    /**
     * Gets the value of the ucpTsignalStrength property.
     * 
     */
    public int getUCPTsignalStrength() {
        return ucpTsignalStrength;
    }

    /**
     * Sets the value of the ucpTsignalStrength property.
     * 
     */
    public void setUCPTsignalStrength(int value) {
        this.ucpTsignalStrength = value;
    }

    /**
     * Gets the value of the ucpTsignalMargin property.
     * 
     */
    public int getUCPTsignalMargin() {
        return ucpTsignalMargin;
    }

    /**
     * Sets the value of the ucpTsignalMargin property.
     * 
     */
    public void setUCPTsignalMargin(int value) {
        this.ucpTsignalMargin = value;
    }

    /**
     * Gets the value of the ucpTsignalUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTsignalUnit() {
        return ucpTsignalUnit;
    }

    /**
     * Sets the value of the ucpTsignalUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTsignalUnit(String value) {
        this.ucpTsignalUnit = value;
    }

}
