//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				ATTENTION: use the 'LON_Device_Command_Invoke' for LON_Device_eCommand:
 * 				'QueryStatus', 'ClearStatus', 'RepeatingData', 'PowerlineData', 'ProxyData', 'PPNData'
 * 			
 * 
 * <p>Java class for LON_Device_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Device_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPThandle" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_UniqueKey" minOccurs="0"/&gt;
 *         &lt;element name="UCPTuniqueId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTreplacementId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTreleaseNId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTprogramId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTgeoPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTlocationId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTauthenticationKey" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmaxDynamicFb" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmaxDynamicDp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmaxTxTransactions" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmaxTxLifetime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UCPTlocal" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *         &lt;element name="UCPTapplicationStatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTcommissionStatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTurlImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTurlTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTdynamic" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTurlCpFile" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="Download" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Address" maxOccurs="2" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTdomainIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTdomainLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTdomainKey" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
 *                   &lt;element name="UCPTsubnet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTnodeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Command" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fault" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Fault" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTcommand" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_eCommand"/&gt;
 *                   &lt;element name="UCPTlastUpdate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTstatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UCPTppnAutoAdded" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *         &lt;element name="RouteCost" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_ePPNRouteCost" minOccurs="0"/&gt;
 *         &lt;element name="ResendPPNSettings" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Device_Cfg", propOrder = {
    "ucpThandle",
    "ucpTuniqueId",
    "ucpTreplacementId",
    "ucpTreleaseNId",
    "ucpTprogramId",
    "ucpTgeoPosition",
    "ucpTlocationId",
    "ucpTauthenticationKey",
    "ucpTmaxDynamicFb",
    "ucpTmaxDynamicDp",
    "ucpTmaxTxTransactions",
    "ucpTmaxTxLifetime",
    "ucpTlocal",
    "ucpTapplicationStatus",
    "ucpTcommissionStatus",
    "ucpTurlImage",
    "ucpTurlTemplate",
    "ucpTdynamic",
    "ucpTurlCpFile",
    "address",
    "command",
    "ucpTppnAutoAdded",
    "routeCost",
    "resendPPNSettings"
})
@XmlSeeAlso({
    LONDeviceNetworkInterfaceCfg.class,
    LONDeviceRNICfg.class,
    LONDeviceRouterCfg.class
})
public class LONDeviceCfg
    extends ItemCfg
{

    @XmlElement(name = "UCPThandle")
    protected EUniqueKey ucpThandle;
    @XmlElement(name = "UCPTuniqueId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTuniqueId;
    @XmlElement(name = "UCPTreplacementId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTreplacementId;
    @XmlElement(name = "UCPTreleaseNId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTreleaseNId;
    @XmlElement(name = "UCPTprogramId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTprogramId;
    @XmlElement(name = "UCPTgeoPosition")
    protected String ucpTgeoPosition;
    @XmlElement(name = "UCPTlocationId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTlocationId;
    @XmlElement(name = "UCPTauthenticationKey", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTauthenticationKey;
    @XmlElement(name = "UCPTmaxDynamicFb")
    protected Integer ucpTmaxDynamicFb;
    @XmlElement(name = "UCPTmaxDynamicDp")
    protected Integer ucpTmaxDynamicDp;
    @XmlElement(name = "UCPTmaxTxTransactions")
    protected Integer ucpTmaxTxTransactions;
    @XmlElement(name = "UCPTmaxTxLifetime")
    protected Integer ucpTmaxTxLifetime;
    @XmlElement(name = "UCPTlocal")
    protected Short ucpTlocal;
    @XmlElement(name = "UCPTapplicationStatus")
    protected ELonString ucpTapplicationStatus;
    @XmlElement(name = "UCPTcommissionStatus")
    protected ELonString ucpTcommissionStatus;
    @XmlElement(name = "UCPTurlImage")
    protected String ucpTurlImage;
    @XmlElement(name = "UCPTurlTemplate")
    protected String ucpTurlTemplate;
    @XmlElement(name = "UCPTdynamic")
    protected ELonString ucpTdynamic;
    @XmlElement(name = "UCPTurlCpFile")
    protected List<LONDeviceCfg.UCPTurlCpFile> ucpTurlCpFile;
    @XmlElement(name = "Address")
    protected List<LONDeviceCfg.Address> address;
    @XmlElement(name = "Command")
    protected List<LONDeviceCfg.Command> command;
    @XmlElement(name = "UCPTppnAutoAdded")
    protected Short ucpTppnAutoAdded;
    @XmlElement(name = "RouteCost")
    protected LONDeviceEPPNRouteCost routeCost;
    @XmlElement(name = "ResendPPNSettings")
    protected Boolean resendPPNSettings;

    /**
     * Gets the value of the ucpThandle property.
     * 
     * @return
     *     possible object is
     *     {@link EUniqueKey }
     *     
     */
    public EUniqueKey getUCPThandle() {
        return ucpThandle;
    }

    /**
     * Sets the value of the ucpThandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUniqueKey }
     *     
     */
    public void setUCPThandle(EUniqueKey value) {
        this.ucpThandle = value;
    }

    /**
     * Gets the value of the ucpTuniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTuniqueId() {
        return ucpTuniqueId;
    }

    /**
     * Sets the value of the ucpTuniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTuniqueId(byte[] value) {
        this.ucpTuniqueId = value;
    }

    /**
     * Gets the value of the ucpTreplacementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTreplacementId() {
        return ucpTreplacementId;
    }

    /**
     * Sets the value of the ucpTreplacementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTreplacementId(byte[] value) {
        this.ucpTreplacementId = value;
    }

    /**
     * Gets the value of the ucpTreleaseNId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTreleaseNId() {
        return ucpTreleaseNId;
    }

    /**
     * Sets the value of the ucpTreleaseNId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTreleaseNId(byte[] value) {
        this.ucpTreleaseNId = value;
    }

    /**
     * Gets the value of the ucpTprogramId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTprogramId() {
        return ucpTprogramId;
    }

    /**
     * Sets the value of the ucpTprogramId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTprogramId(byte[] value) {
        this.ucpTprogramId = value;
    }

    /**
     * Gets the value of the ucpTgeoPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTgeoPosition() {
        return ucpTgeoPosition;
    }

    /**
     * Sets the value of the ucpTgeoPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTgeoPosition(String value) {
        this.ucpTgeoPosition = value;
    }

    /**
     * Gets the value of the ucpTlocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTlocationId() {
        return ucpTlocationId;
    }

    /**
     * Sets the value of the ucpTlocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTlocationId(byte[] value) {
        this.ucpTlocationId = value;
    }

    /**
     * Gets the value of the ucpTauthenticationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTauthenticationKey() {
        return ucpTauthenticationKey;
    }

    /**
     * Sets the value of the ucpTauthenticationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTauthenticationKey(byte[] value) {
        this.ucpTauthenticationKey = value;
    }

    /**
     * Gets the value of the ucpTmaxDynamicFb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTmaxDynamicFb() {
        return ucpTmaxDynamicFb;
    }

    /**
     * Sets the value of the ucpTmaxDynamicFb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTmaxDynamicFb(Integer value) {
        this.ucpTmaxDynamicFb = value;
    }

    /**
     * Gets the value of the ucpTmaxDynamicDp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTmaxDynamicDp() {
        return ucpTmaxDynamicDp;
    }

    /**
     * Sets the value of the ucpTmaxDynamicDp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTmaxDynamicDp(Integer value) {
        this.ucpTmaxDynamicDp = value;
    }

    /**
     * Gets the value of the ucpTmaxTxTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTmaxTxTransactions() {
        return ucpTmaxTxTransactions;
    }

    /**
     * Sets the value of the ucpTmaxTxTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTmaxTxTransactions(Integer value) {
        this.ucpTmaxTxTransactions = value;
    }

    /**
     * Gets the value of the ucpTmaxTxLifetime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTmaxTxLifetime() {
        return ucpTmaxTxLifetime;
    }

    /**
     * Sets the value of the ucpTmaxTxLifetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTmaxTxLifetime(Integer value) {
        this.ucpTmaxTxLifetime = value;
    }

    /**
     * Gets the value of the ucpTlocal property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUCPTlocal() {
        return ucpTlocal;
    }

    /**
     * Sets the value of the ucpTlocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUCPTlocal(Short value) {
        this.ucpTlocal = value;
    }

    /**
     * Gets the value of the ucpTapplicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTapplicationStatus() {
        return ucpTapplicationStatus;
    }

    /**
     * Sets the value of the ucpTapplicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTapplicationStatus(ELonString value) {
        this.ucpTapplicationStatus = value;
    }

    /**
     * Gets the value of the ucpTcommissionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTcommissionStatus() {
        return ucpTcommissionStatus;
    }

    /**
     * Sets the value of the ucpTcommissionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTcommissionStatus(ELonString value) {
        this.ucpTcommissionStatus = value;
    }

    /**
     * Gets the value of the ucpTurlImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTurlImage() {
        return ucpTurlImage;
    }

    /**
     * Sets the value of the ucpTurlImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTurlImage(String value) {
        this.ucpTurlImage = value;
    }

    /**
     * Gets the value of the ucpTurlTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTurlTemplate() {
        return ucpTurlTemplate;
    }

    /**
     * Sets the value of the ucpTurlTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTurlTemplate(String value) {
        this.ucpTurlTemplate = value;
    }

    /**
     * Gets the value of the ucpTdynamic property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTdynamic() {
        return ucpTdynamic;
    }

    /**
     * Sets the value of the ucpTdynamic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTdynamic(ELonString value) {
        this.ucpTdynamic = value;
    }

    /**
     * Gets the value of the ucpTurlCpFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ucpTurlCpFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUCPTurlCpFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONDeviceCfg.UCPTurlCpFile }
     * 
     * 
     */
    public List<LONDeviceCfg.UCPTurlCpFile> getUCPTurlCpFile() {
        if (ucpTurlCpFile == null) {
            ucpTurlCpFile = new ArrayList<LONDeviceCfg.UCPTurlCpFile>();
        }
        return this.ucpTurlCpFile;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONDeviceCfg.Address }
     * 
     * 
     */
    public List<LONDeviceCfg.Address> getAddress() {
        if (address == null) {
            address = new ArrayList<LONDeviceCfg.Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the command property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the command property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONDeviceCfg.Command }
     * 
     * 
     */
    public List<LONDeviceCfg.Command> getCommand() {
        if (command == null) {
            command = new ArrayList<LONDeviceCfg.Command>();
        }
        return this.command;
    }

    /**
     * Gets the value of the ucpTppnAutoAdded property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUCPTppnAutoAdded() {
        return ucpTppnAutoAdded;
    }

    /**
     * Sets the value of the ucpTppnAutoAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUCPTppnAutoAdded(Short value) {
        this.ucpTppnAutoAdded = value;
    }

    /**
     * Gets the value of the routeCost property.
     * 
     * @return
     *     possible object is
     *     {@link LONDeviceEPPNRouteCost }
     *     
     */
    public LONDeviceEPPNRouteCost getRouteCost() {
        return routeCost;
    }

    /**
     * Sets the value of the routeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link LONDeviceEPPNRouteCost }
     *     
     */
    public void setRouteCost(LONDeviceEPPNRouteCost value) {
        this.routeCost = value;
    }

    /**
     * Gets the value of the resendPPNSettings property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResendPPNSettings() {
        return resendPPNSettings;
    }

    /**
     * Sets the value of the resendPPNSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResendPPNSettings(Boolean value) {
        this.resendPPNSettings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTdomainIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTdomainLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTdomainKey" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
     *         &lt;element name="UCPTsubnet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTnodeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTdomainIndex",
        "ucpTdomainLength",
        "ucpTdomainKey",
        "ucpTsubnet",
        "ucpTnodeId"
    })
    public static class Address {

        @XmlElement(name = "UCPTdomainIndex")
        protected Integer ucpTdomainIndex;
        @XmlElement(name = "UCPTdomainLength")
        protected int ucpTdomainLength;
        @XmlElement(name = "UCPTdomainKey", required = true, type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] ucpTdomainKey;
        @XmlElement(name = "UCPTsubnet")
        protected Integer ucpTsubnet;
        @XmlElement(name = "UCPTnodeId")
        protected Integer ucpTnodeId;

        /**
         * Gets the value of the ucpTdomainIndex property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTdomainIndex() {
            return ucpTdomainIndex;
        }

        /**
         * Sets the value of the ucpTdomainIndex property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTdomainIndex(Integer value) {
            this.ucpTdomainIndex = value;
        }

        /**
         * Gets the value of the ucpTdomainLength property.
         * 
         */
        public int getUCPTdomainLength() {
            return ucpTdomainLength;
        }

        /**
         * Sets the value of the ucpTdomainLength property.
         * 
         */
        public void setUCPTdomainLength(int value) {
            this.ucpTdomainLength = value;
        }

        /**
         * Gets the value of the ucpTdomainKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getUCPTdomainKey() {
            return ucpTdomainKey;
        }

        /**
         * Sets the value of the ucpTdomainKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTdomainKey(byte[] value) {
            this.ucpTdomainKey = value;
        }

        /**
         * Gets the value of the ucpTsubnet property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTsubnet() {
            return ucpTsubnet;
        }

        /**
         * Sets the value of the ucpTsubnet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTsubnet(Integer value) {
            this.ucpTsubnet = value;
        }

        /**
         * Gets the value of the ucpTnodeId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTnodeId() {
            return ucpTnodeId;
        }

        /**
         * Sets the value of the ucpTnodeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTnodeId(Integer value) {
            this.ucpTnodeId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fault" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Fault" minOccurs="0"/&gt;
     *         &lt;element name="UCPTcommand" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Device_eCommand"/&gt;
     *         &lt;element name="UCPTlastUpdate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="UCPTstatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fault",
        "ucpTcommand",
        "ucpTlastUpdate",
        "ucpTstatus"
    })
    public static class Command {

        protected EFault fault;
        @XmlElement(name = "UCPTcommand", required = true)
        @XmlSchemaType(name = "string")
        protected LONDeviceECommand ucpTcommand;
        @XmlElement(name = "UCPTlastUpdate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar ucpTlastUpdate;
        @XmlElement(name = "UCPTstatus")
        protected ELonString ucpTstatus;

        /**
         * Gets the value of the fault property.
         * 
         * @return
         *     possible object is
         *     {@link EFault }
         *     
         */
        public EFault getFault() {
            return fault;
        }

        /**
         * Sets the value of the fault property.
         * 
         * @param value
         *     allowed object is
         *     {@link EFault }
         *     
         */
        public void setFault(EFault value) {
            this.fault = value;
        }

        /**
         * Gets the value of the ucpTcommand property.
         * 
         * @return
         *     possible object is
         *     {@link LONDeviceECommand }
         *     
         */
        public LONDeviceECommand getUCPTcommand() {
            return ucpTcommand;
        }

        /**
         * Sets the value of the ucpTcommand property.
         * 
         * @param value
         *     allowed object is
         *     {@link LONDeviceECommand }
         *     
         */
        public void setUCPTcommand(LONDeviceECommand value) {
            this.ucpTcommand = value;
        }

        /**
         * Gets the value of the ucpTlastUpdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getUCPTlastUpdate() {
            return ucpTlastUpdate;
        }

        /**
         * Sets the value of the ucpTlastUpdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setUCPTlastUpdate(XMLGregorianCalendar value) {
            this.ucpTlastUpdate = value;
        }

        /**
         * Gets the value of the ucpTstatus property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTstatus() {
            return ucpTstatus;
        }

        /**
         * Sets the value of the ucpTstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTstatus(ELonString value) {
            this.ucpTstatus = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="Download" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class UCPTurlCpFile {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Download")
        protected Boolean download;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the download property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isDownload() {
            return download;
        }

        /**
         * Sets the value of the download property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDownload(Boolean value) {
            this.download = value;
        }

    }

}
