//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Specialized functional block configuration type.
 * 					Example:  xSelect="//Item[@xsi:type="LON_Fb_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="LON_Fb_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for LON_Fb_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Fb_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTfbIndex" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_UniqueKey" minOccurs="0"/&gt;
 *         &lt;element name="UCPTfptKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTdynamic" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Fb_Cfg", propOrder = {
    "ucpTfbIndex",
    "ucpTfptKey",
    "ucpTdynamic"
})
public class LONFbCfg
    extends FbCfg
{

    @XmlElement(name = "UCPTfbIndex")
    protected EUniqueKey ucpTfbIndex;
    @XmlElement(name = "UCPTfptKey")
    protected String ucpTfptKey;
    @XmlElement(name = "UCPTdynamic")
    protected ELonString ucpTdynamic;

    /**
     * Gets the value of the ucpTfbIndex property.
     * 
     * @return
     *     possible object is
     *     {@link EUniqueKey }
     *     
     */
    public EUniqueKey getUCPTfbIndex() {
        return ucpTfbIndex;
    }

    /**
     * Sets the value of the ucpTfbIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUniqueKey }
     *     
     */
    public void setUCPTfbIndex(EUniqueKey value) {
        this.ucpTfbIndex = value;
    }

    /**
     * Gets the value of the ucpTfptKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTfptKey() {
        return ucpTfptKey;
    }

    /**
     * Sets the value of the ucpTfptKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTfptKey(String value) {
        this.ucpTfptKey = value;
    }

    /**
     * Gets the value of the ucpTdynamic property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTdynamic() {
        return ucpTdynamic;
    }

    /**
     * Sets the value of the ucpTdynamic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTdynamic(ELonString value) {
        this.ucpTdynamic = value;
    }

}
