//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				LON specific network command (called with 'InvokeCmd' operation).
 * 			
 * 
 * <p>Java class for LON_Network_Command_Invoke complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Network_Command_Invoke"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item"&gt;
 *       &lt;attribute name="Command" use="required" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Network_eCommand" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Network_Command_Invoke")
@XmlSeeAlso({
    LONNetworkPPNBlacklistInvoke.class
})
public class LONNetworkCommandInvoke
    extends Item
{

    @XmlAttribute(name = "Command", required = true)
    protected LONNetworkECommand command;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link LONNetworkECommand }
     *     
     */
    public LONNetworkECommand getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link LONNetworkECommand }
     *     
     */
    public void setCommand(LONNetworkECommand value) {
        this.command = value;
    }

}
