//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			LON specific network command (called with 'InvokeCmd' operation).
 * 		
 * 
 * <p>Java class for LON_Network_PPNBlacklist_Invoke complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LON_Network_PPNBlacklist_Invoke"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}LON_Network_Command_Invoke"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Entry" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTmacID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTdefaultPni" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LON_Network_PPNBlacklist_Invoke", propOrder = {
    "entry"
})
public class LONNetworkPPNBlacklistInvoke
    extends LONNetworkCommandInvoke
{

    @XmlElement(name = "Entry")
    protected List<LONNetworkPPNBlacklistInvoke.Entry> entry;

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONNetworkPPNBlacklistInvoke.Entry }
     * 
     * 
     */
    public List<LONNetworkPPNBlacklistInvoke.Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<LONNetworkPPNBlacklistInvoke.Entry>();
        }
        return this.entry;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTmacID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTdefaultPni" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTmacID",
        "ucpTdefaultPni"
    })
    public static class Entry {

        @XmlElement(name = "UCPTmacID", required = true)
        protected String ucpTmacID;
        @XmlElement(name = "UCPTdefaultPni")
        @XmlSchemaType(name = "unsignedInt")
        protected long ucpTdefaultPni;

        /**
         * Gets the value of the ucpTmacID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTmacID() {
            return ucpTmacID;
        }

        /**
         * Sets the value of the ucpTmacID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTmacID(String value) {
            this.ucpTmacID = value;
        }

        /**
         * Gets the value of the ucpTdefaultPni property.
         * 
         */
        public long getUCPTdefaultPni() {
            return ucpTdefaultPni;
        }

        /**
         * Sets the value of the ucpTdefaultPni property.
         * 
         */
        public void setUCPTdefaultPni(long value) {
            this.ucpTdefaultPni = value;
        }

    }

}
