//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LON_Network_eScanCommand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LON_Network_eScanCommand"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GetScan"/&gt;
 *     &lt;enumeration value="SetScan"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LON_Network_eScanCommand")
@XmlEnum
public enum LONNetworkEScanCommand {

    @XmlEnumValue("GetScan")
    GET_SCAN("GetScan"),
    @XmlEnumValue("SetScan")
    SET_SCAN("SetScan");
    private final String value;

    LONNetworkEScanCommand(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LONNetworkEScanCommand fromValue(String v) {
        for (LONNetworkEScanCommand c: LONNetworkEScanCommand.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
