//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 				Specialized device configuration type.
 * 					Example:  xSelect="//Item[@xsi:type="MBS_Device_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="MBS_Device_Cfg"][starts-with(UCPTname,'Net/MBS/')]"
 * 			
 * 
 * <p>Java class for MBS_Device_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MBS_Device_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPThandle" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_UniqueKey" minOccurs="0"/&gt;
 *         &lt;element name="UCPTprogramId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="UCPTspeed" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTmbusFcbEnable" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmbusFcvEnable" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmbusMode" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmbusMedId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmbusManId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmbusGenId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Address" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTmbusAddressTyp" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                   &lt;element name="UCPTmbusPrimaryAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTmbusSecondaryAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MBS_Device_Cfg", propOrder = {
    "ucpThandle",
    "ucpTprogramId",
    "ucpTspeed",
    "ucpTmbusFcbEnable",
    "ucpTmbusFcvEnable",
    "ucpTmbusMode",
    "ucpTmbusMedId",
    "ucpTmbusManId",
    "ucpTmbusGenId",
    "address"
})
public class MBSDeviceCfg
    extends ItemCfg
{

    @XmlElement(name = "UCPThandle")
    protected EUniqueKey ucpThandle;
    @XmlElement(name = "UCPTprogramId", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] ucpTprogramId;
    @XmlElement(name = "UCPTspeed", required = true)
    protected ELonString ucpTspeed;
    @XmlElement(name = "UCPTmbusFcbEnable")
    protected Short ucpTmbusFcbEnable;
    @XmlElement(name = "UCPTmbusFcvEnable")
    protected Short ucpTmbusFcvEnable;
    @XmlElement(name = "UCPTmbusMode")
    protected ELonString ucpTmbusMode;
    @XmlElement(name = "UCPTmbusMedId")
    protected String ucpTmbusMedId;
    @XmlElement(name = "UCPTmbusManId")
    protected String ucpTmbusManId;
    @XmlElement(name = "UCPTmbusGenId")
    protected String ucpTmbusGenId;
    @XmlElement(name = "Address")
    protected MBSDeviceCfg.Address address;

    /**
     * Gets the value of the ucpThandle property.
     * 
     * @return
     *     possible object is
     *     {@link EUniqueKey }
     *     
     */
    public EUniqueKey getUCPThandle() {
        return ucpThandle;
    }

    /**
     * Sets the value of the ucpThandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUniqueKey }
     *     
     */
    public void setUCPThandle(EUniqueKey value) {
        this.ucpThandle = value;
    }

    /**
     * Gets the value of the ucpTprogramId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getUCPTprogramId() {
        return ucpTprogramId;
    }

    /**
     * Sets the value of the ucpTprogramId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTprogramId(byte[] value) {
        this.ucpTprogramId = value;
    }

    /**
     * Gets the value of the ucpTspeed property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTspeed() {
        return ucpTspeed;
    }

    /**
     * Sets the value of the ucpTspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTspeed(ELonString value) {
        this.ucpTspeed = value;
    }

    /**
     * Gets the value of the ucpTmbusFcbEnable property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUCPTmbusFcbEnable() {
        return ucpTmbusFcbEnable;
    }

    /**
     * Sets the value of the ucpTmbusFcbEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUCPTmbusFcbEnable(Short value) {
        this.ucpTmbusFcbEnable = value;
    }

    /**
     * Gets the value of the ucpTmbusFcvEnable property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUCPTmbusFcvEnable() {
        return ucpTmbusFcvEnable;
    }

    /**
     * Sets the value of the ucpTmbusFcvEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUCPTmbusFcvEnable(Short value) {
        this.ucpTmbusFcvEnable = value;
    }

    /**
     * Gets the value of the ucpTmbusMode property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTmbusMode() {
        return ucpTmbusMode;
    }

    /**
     * Sets the value of the ucpTmbusMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTmbusMode(ELonString value) {
        this.ucpTmbusMode = value;
    }

    /**
     * Gets the value of the ucpTmbusMedId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTmbusMedId() {
        return ucpTmbusMedId;
    }

    /**
     * Sets the value of the ucpTmbusMedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTmbusMedId(String value) {
        this.ucpTmbusMedId = value;
    }

    /**
     * Gets the value of the ucpTmbusManId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTmbusManId() {
        return ucpTmbusManId;
    }

    /**
     * Sets the value of the ucpTmbusManId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTmbusManId(String value) {
        this.ucpTmbusManId = value;
    }

    /**
     * Gets the value of the ucpTmbusGenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTmbusGenId() {
        return ucpTmbusGenId;
    }

    /**
     * Sets the value of the ucpTmbusGenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTmbusGenId(String value) {
        this.ucpTmbusGenId = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link MBSDeviceCfg.Address }
     *     
     */
    public MBSDeviceCfg.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBSDeviceCfg.Address }
     *     
     */
    public void setAddress(MBSDeviceCfg.Address value) {
        this.address = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTmbusAddressTyp" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *         &lt;element name="UCPTmbusPrimaryAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTmbusSecondaryAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTmbusAddressTyp",
        "ucpTmbusPrimaryAddress",
        "ucpTmbusSecondaryAddress"
    })
    public static class Address {

        @XmlElement(name = "UCPTmbusAddressTyp", required = true)
        protected ELonString ucpTmbusAddressTyp;
        @XmlElement(name = "UCPTmbusPrimaryAddress", required = true)
        protected String ucpTmbusPrimaryAddress;
        @XmlElement(name = "UCPTmbusSecondaryAddress", required = true)
        protected String ucpTmbusSecondaryAddress;

        /**
         * Gets the value of the ucpTmbusAddressTyp property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTmbusAddressTyp() {
            return ucpTmbusAddressTyp;
        }

        /**
         * Sets the value of the ucpTmbusAddressTyp property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTmbusAddressTyp(ELonString value) {
            this.ucpTmbusAddressTyp = value;
        }

        /**
         * Gets the value of the ucpTmbusPrimaryAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTmbusPrimaryAddress() {
            return ucpTmbusPrimaryAddress;
        }

        /**
         * Sets the value of the ucpTmbusPrimaryAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTmbusPrimaryAddress(String value) {
            this.ucpTmbusPrimaryAddress = value;
        }

        /**
         * Gets the value of the ucpTmbusSecondaryAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTmbusSecondaryAddress() {
            return ucpTmbusSecondaryAddress;
        }

        /**
         * Sets the value of the ucpTmbusSecondaryAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTmbusSecondaryAddress(String value) {
            this.ucpTmbusSecondaryAddress = value;
        }

    }

}
