//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Specialized channel configuration type.
 * 					Example:  xSelect="//Item[@xsi:type="MOD_Channel_Cfg"]"
 * 			
 * 
 * <p>Java class for MOD_Channel_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MOD_Channel_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPThandle" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_UniqueKey" minOccurs="0"/&gt;
 *         &lt;element name="UCPTchannelType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTport" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="InterfaceOptions" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_InterfaceOptions" minOccurs="0"/&gt;
 *         &lt;element name="UCPTserialMode" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTretryCount" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTminOfflineTime" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTassembleTime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="UCPTtimeout" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MOD_Channel_Cfg", propOrder = {
    "ucpThandle",
    "ucpTchannelType",
    "ucpTport",
    "interfaceOptions",
    "ucpTserialMode",
    "ucpTretryCount",
    "ucpTminOfflineTime",
    "ucpTassembleTime",
    "ucpTtimeout"
})
public class MODChannelCfg
    extends ItemCfg
{

    @XmlElement(name = "UCPThandle")
    protected EUniqueKey ucpThandle;
    @XmlElement(name = "UCPTchannelType", required = true)
    protected ELonString ucpTchannelType;
    @XmlElement(name = "UCPTport")
    protected Integer ucpTport;
    @XmlElement(name = "InterfaceOptions")
    protected EInterfaceOptions interfaceOptions;
    @XmlElement(name = "UCPTserialMode")
    protected ELonString ucpTserialMode;
    @XmlElement(name = "UCPTretryCount")
    protected ELonString ucpTretryCount;
    @XmlElement(name = "UCPTminOfflineTime")
    protected ELonString ucpTminOfflineTime;
    @XmlElement(name = "UCPTassembleTime")
    @XmlSchemaType(name = "unsignedInt")
    protected Long ucpTassembleTime;
    @XmlElement(name = "UCPTtimeout")
    @XmlSchemaType(name = "unsignedInt")
    protected Long ucpTtimeout;

    /**
     * Gets the value of the ucpThandle property.
     * 
     * @return
     *     possible object is
     *     {@link EUniqueKey }
     *     
     */
    public EUniqueKey getUCPThandle() {
        return ucpThandle;
    }

    /**
     * Sets the value of the ucpThandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUniqueKey }
     *     
     */
    public void setUCPThandle(EUniqueKey value) {
        this.ucpThandle = value;
    }

    /**
     * Gets the value of the ucpTchannelType property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTchannelType() {
        return ucpTchannelType;
    }

    /**
     * Sets the value of the ucpTchannelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTchannelType(ELonString value) {
        this.ucpTchannelType = value;
    }

    /**
     * Gets the value of the ucpTport property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTport() {
        return ucpTport;
    }

    /**
     * Sets the value of the ucpTport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTport(Integer value) {
        this.ucpTport = value;
    }

    /**
     * Gets the value of the interfaceOptions property.
     * 
     * @return
     *     possible object is
     *     {@link EInterfaceOptions }
     *     
     */
    public EInterfaceOptions getInterfaceOptions() {
        return interfaceOptions;
    }

    /**
     * Sets the value of the interfaceOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EInterfaceOptions }
     *     
     */
    public void setInterfaceOptions(EInterfaceOptions value) {
        this.interfaceOptions = value;
    }

    /**
     * Gets the value of the ucpTserialMode property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTserialMode() {
        return ucpTserialMode;
    }

    /**
     * Sets the value of the ucpTserialMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTserialMode(ELonString value) {
        this.ucpTserialMode = value;
    }

    /**
     * Gets the value of the ucpTretryCount property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTretryCount() {
        return ucpTretryCount;
    }

    /**
     * Sets the value of the ucpTretryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTretryCount(ELonString value) {
        this.ucpTretryCount = value;
    }

    /**
     * Gets the value of the ucpTminOfflineTime property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTminOfflineTime() {
        return ucpTminOfflineTime;
    }

    /**
     * Sets the value of the ucpTminOfflineTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTminOfflineTime(ELonString value) {
        this.ucpTminOfflineTime = value;
    }

    /**
     * Gets the value of the ucpTassembleTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUCPTassembleTime() {
        return ucpTassembleTime;
    }

    /**
     * Sets the value of the ucpTassembleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUCPTassembleTime(Long value) {
        this.ucpTassembleTime = value;
    }

    /**
     * Gets the value of the ucpTtimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUCPTtimeout() {
        return ucpTtimeout;
    }

    /**
     * Sets the value of the ucpTtimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUCPTtimeout(Long value) {
        this.ucpTtimeout = value;
    }

}
