//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sahil.iLON.toggle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sahil.iLON.toggle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MBSDeviceCfg }
     * 
     */
    public MBSDeviceCfg createMBSDeviceCfg() {
        return new MBSDeviceCfg();
    }

    /**
     * Create an instance of {@link MODDeviceCfg }
     * 
     */
    public MODDeviceCfg createMODDeviceCfg() {
        return new MODDeviceCfg();
    }

    /**
     * Create an instance of {@link LONDeviceProxyDataInvokeResponse }
     * 
     */
    public LONDeviceProxyDataInvokeResponse createLONDeviceProxyDataInvokeResponse() {
        return new LONDeviceProxyDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONDeviceRepeatingDataInvokeResponse }
     * 
     */
    public LONDeviceRepeatingDataInvokeResponse createLONDeviceRepeatingDataInvokeResponse() {
        return new LONDeviceRepeatingDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONNetworkPPNBlacklistInvoke }
     * 
     */
    public LONNetworkPPNBlacklistInvoke createLONNetworkPPNBlacklistInvoke() {
        return new LONNetworkPPNBlacklistInvoke();
    }

    /**
     * Create an instance of {@link LONNetworkScanCommandInvoke }
     * 
     */
    public LONNetworkScanCommandInvoke createLONNetworkScanCommandInvoke() {
        return new LONNetworkScanCommandInvoke();
    }

    /**
     * Create an instance of {@link LONDeviceCfg }
     * 
     */
    public LONDeviceCfg createLONDeviceCfg() {
        return new LONDeviceCfg();
    }

    /**
     * Create an instance of {@link LONNetworkCfg }
     * 
     */
    public LONNetworkCfg createLONNetworkCfg() {
        return new LONNetworkCfg();
    }

    /**
     * Create an instance of {@link DpRef }
     * 
     */
    public DpRef createDpRef() {
        return new DpRef();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgStruct }
     * 
     */
    public TemplateManagerCfgStruct createTemplateManagerCfgStruct() {
        return new TemplateManagerCfgStruct();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgBitfield }
     * 
     */
    public TemplateManagerCfgBitfield createTemplateManagerCfgBitfield() {
        return new TemplateManagerCfgBitfield();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgScalar }
     * 
     */
    public TemplateManagerCfgScalar createTemplateManagerCfgScalar() {
        return new TemplateManagerCfgScalar();
    }

    /**
     * Create an instance of {@link TemplateManagerFPTCfg }
     * 
     */
    public TemplateManagerFPTCfg createTemplateManagerFPTCfg() {
        return new TemplateManagerFPTCfg();
    }

    /**
     * Create an instance of {@link TemplateManagerENUMCfg }
     * 
     */
    public TemplateManagerENUMCfg createTemplateManagerENUMCfg() {
        return new TemplateManagerENUMCfg();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorRuleCfg }
     * 
     */
    public UFPTtypeTranslatorRuleCfg createUFPTtypeTranslatorRuleCfg() {
        return new UFPTtypeTranslatorRuleCfg();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorRuleCfg.Case }
     * 
     */
    public UFPTtypeTranslatorRuleCfg.Case createUFPTtypeTranslatorRuleCfgCase() {
        return new UFPTtypeTranslatorRuleCfg.Case();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfg }
     * 
     */
    public UFPTschedulerCfg createUFPTschedulerCfg() {
        return new UFPTschedulerCfg();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfg.DateBased }
     * 
     */
    public UFPTschedulerCfg.DateBased createUFPTschedulerCfgDateBased() {
        return new UFPTschedulerCfg.DateBased();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfg.DayBased }
     * 
     */
    public UFPTschedulerCfg.DayBased createUFPTschedulerCfgDayBased() {
        return new UFPTschedulerCfg.DayBased();
    }

    /**
     * Create an instance of {@link UFPTcalendarCfg }
     * 
     */
    public UFPTcalendarCfg createUFPTcalendarCfg() {
        return new UFPTcalendarCfg();
    }

    /**
     * Create an instance of {@link UFPTcalendarCfg.Exception }
     * 
     */
    public UFPTcalendarCfg.Exception createUFPTcalendarCfgException() {
        return new UFPTcalendarCfg.Exception();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierData }
     * 
     */
    public UFPTalarmNotifierData createUFPTalarmNotifierData() {
        return new UFPTalarmNotifierData();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierInputDpRef }
     * 
     */
    public UFPTalarmNotifierInputDpRef createUFPTalarmNotifierInputDpRef() {
        return new UFPTalarmNotifierInputDpRef();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierCfg }
     * 
     */
    public UFPTalarmNotifierCfg createUFPTalarmNotifierCfg() {
        return new UFPTalarmNotifierCfg();
    }

    /**
     * Create an instance of {@link EVariant }
     * 
     */
    public EVariant createEVariant() {
        return new EVariant();
    }

    /**
     * Create an instance of {@link EFault }
     * 
     */
    public EFault createEFault() {
        return new EFault();
    }

    /**
     * Create an instance of {@link MessageProperties }
     * 
     */
    public MessageProperties createMessageProperties() {
        return new MessageProperties();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link EXSelect }
     * 
     */
    public EXSelect createEXSelect() {
        return new EXSelect();
    }

    /**
     * Create an instance of {@link ListResponse }
     * 
     */
    public ListResponse createListResponse() {
        return new ListResponse();
    }

    /**
     * Create an instance of {@link ItemColl }
     * 
     */
    public ItemColl createItemColl() {
        return new ItemColl();
    }

    /**
     * Create an instance of {@link Get }
     * 
     */
    public Get createGet() {
        return new Get();
    }

    /**
     * Create an instance of {@link GetResponse }
     * 
     */
    public GetResponse createGetResponse() {
        return new GetResponse();
    }

    /**
     * Create an instance of {@link ItemCfgColl }
     * 
     */
    public ItemCfgColl createItemCfgColl() {
        return new ItemCfgColl();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link SetResponse }
     * 
     */
    public SetResponse createSetResponse() {
        return new SetResponse();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link DeleteResponse }
     * 
     */
    public DeleteResponse createDeleteResponse() {
        return new DeleteResponse();
    }

    /**
     * Create an instance of {@link Read }
     * 
     */
    public Read createRead() {
        return new Read();
    }

    /**
     * Create an instance of {@link ReadResponse }
     * 
     */
    public ReadResponse createReadResponse() {
        return new ReadResponse();
    }

    /**
     * Create an instance of {@link ItemDataColl }
     * 
     */
    public ItemDataColl createItemDataColl() {
        return new ItemDataColl();
    }

    /**
     * Create an instance of {@link Write }
     * 
     */
    public Write createWrite() {
        return new Write();
    }

    /**
     * Create an instance of {@link WriteResponse }
     * 
     */
    public WriteResponse createWriteResponse() {
        return new WriteResponse();
    }

    /**
     * Create an instance of {@link Clear }
     * 
     */
    public Clear createClear() {
        return new Clear();
    }

    /**
     * Create an instance of {@link ClearResponse }
     * 
     */
    public ClearResponse createClearResponse() {
        return new ClearResponse();
    }

    /**
     * Create an instance of {@link InvokeCmd }
     * 
     */
    public InvokeCmd createInvokeCmd() {
        return new InvokeCmd();
    }

    /**
     * Create an instance of {@link InvokeCmdResponse }
     * 
     */
    public InvokeCmdResponse createInvokeCmdResponse() {
        return new InvokeCmdResponse();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ItemCfg }
     * 
     */
    public ItemCfg createItemCfg() {
        return new ItemCfg();
    }

    /**
     * Create an instance of {@link ItemData }
     * 
     */
    public ItemData createItemData() {
        return new ItemData();
    }

    /**
     * Create an instance of {@link ItemService }
     * 
     */
    public ItemService createItemService() {
        return new ItemService();
    }

    /**
     * Create an instance of {@link EDpRef }
     * 
     */
    public EDpRef createEDpRef() {
        return new EDpRef();
    }

    /**
     * Create an instance of {@link ELonString }
     * 
     */
    public ELonString createELonString() {
        return new ELonString();
    }

    /**
     * Create an instance of {@link EUniqueKey }
     * 
     */
    public EUniqueKey createEUniqueKey() {
        return new EUniqueKey();
    }

    /**
     * Create an instance of {@link EPath }
     * 
     */
    public EPath createEPath() {
        return new EPath();
    }

    /**
     * Create an instance of {@link EUnit }
     * 
     */
    public EUnit createEUnit() {
        return new EUnit();
    }

    /**
     * Create an instance of {@link EInterfaceOptions }
     * 
     */
    public EInterfaceOptions createEInterfaceOptions() {
        return new EInterfaceOptions();
    }

    /**
     * Create an instance of {@link NetworkCfg }
     * 
     */
    public NetworkCfg createNetworkCfg() {
        return new NetworkCfg();
    }

    /**
     * Create an instance of {@link ChannelCfg }
     * 
     */
    public ChannelCfg createChannelCfg() {
        return new ChannelCfg();
    }

    /**
     * Create an instance of {@link DeviceCfg }
     * 
     */
    public DeviceCfg createDeviceCfg() {
        return new DeviceCfg();
    }

    /**
     * Create an instance of {@link FbCfg }
     * 
     */
    public FbCfg createFbCfg() {
        return new FbCfg();
    }

    /**
     * Create an instance of {@link DpCfg }
     * 
     */
    public DpCfg createDpCfg() {
        return new DpCfg();
    }

    /**
     * Create an instance of {@link DpCfgValueDef }
     * 
     */
    public DpCfgValueDef createDpCfgValueDef() {
        return new DpCfgValueDef();
    }

    /**
     * Create an instance of {@link DpData }
     * 
     */
    public DpData createDpData() {
        return new DpData();
    }

    /**
     * Create an instance of {@link DpResetPrioInvoke }
     * 
     */
    public DpResetPrioInvoke createDpResetPrioInvoke() {
        return new DpResetPrioInvoke();
    }

    /**
     * Create an instance of {@link FPMCfg }
     * 
     */
    public FPMCfg createFPMCfg() {
        return new FPMCfg();
    }

    /**
     * Create an instance of {@link UFPTanalogFunctionBlockCfg }
     * 
     */
    public UFPTanalogFunctionBlockCfg createUFPTanalogFunctionBlockCfg() {
        return new UFPTanalogFunctionBlockCfg();
    }

    /**
     * Create an instance of {@link UFPTanalogFunctionBlockDpRef }
     * 
     */
    public UFPTanalogFunctionBlockDpRef createUFPTanalogFunctionBlockDpRef() {
        return new UFPTanalogFunctionBlockDpRef();
    }

    /**
     * Create an instance of {@link UFPTalarmGeneratorCfg }
     * 
     */
    public UFPTalarmGeneratorCfg createUFPTalarmGeneratorCfg() {
        return new UFPTalarmGeneratorCfg();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierDpRef }
     * 
     */
    public UFPTalarmNotifierDpRef createUFPTalarmNotifierDpRef() {
        return new UFPTalarmNotifierDpRef();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierCfgAlarm }
     * 
     */
    public UFPTalarmNotifierCfgAlarm createUFPTalarmNotifierCfgAlarm() {
        return new UFPTalarmNotifierCfgAlarm();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierCfgAlarmDestination }
     * 
     */
    public UFPTalarmNotifierCfgAlarmDestination createUFPTalarmNotifierCfgAlarmDestination() {
        return new UFPTalarmNotifierCfgAlarmDestination();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierMetaData }
     * 
     */
    public UFPTalarmNotifierMetaData createUFPTalarmNotifierMetaData() {
        return new UFPTalarmNotifierMetaData();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierClearResponse }
     * 
     */
    public UFPTalarmNotifierClearResponse createUFPTalarmNotifierClearResponse() {
        return new UFPTalarmNotifierClearResponse();
    }

    /**
     * Create an instance of {@link UFPTcalendarCfgESDate }
     * 
     */
    public UFPTcalendarCfgESDate createUFPTcalendarCfgESDate() {
        return new UFPTcalendarCfgESDate();
    }

    /**
     * Create an instance of {@link UFPTcalendarData }
     * 
     */
    public UFPTcalendarData createUFPTcalendarData() {
        return new UFPTcalendarData();
    }

    /**
     * Create an instance of {@link UFPTdataLoggerCfg }
     * 
     */
    public UFPTdataLoggerCfg createUFPTdataLoggerCfg() {
        return new UFPTdataLoggerCfg();
    }

    /**
     * Create an instance of {@link UFPTdataLoggerDpRef }
     * 
     */
    public UFPTdataLoggerDpRef createUFPTdataLoggerDpRef() {
        return new UFPTdataLoggerDpRef();
    }

    /**
     * Create an instance of {@link UFPTdataLoggerData }
     * 
     */
    public UFPTdataLoggerData createUFPTdataLoggerData() {
        return new UFPTdataLoggerData();
    }

    /**
     * Create an instance of {@link UFPTdataLoggerMetaData }
     * 
     */
    public UFPTdataLoggerMetaData createUFPTdataLoggerMetaData() {
        return new UFPTdataLoggerMetaData();
    }

    /**
     * Create an instance of {@link UFPTdataLoggerClearResponse }
     * 
     */
    public UFPTdataLoggerClearResponse createUFPTdataLoggerClearResponse() {
        return new UFPTdataLoggerClearResponse();
    }

    /**
     * Create an instance of {@link UFPTdigitalInputCfg }
     * 
     */
    public UFPTdigitalInputCfg createUFPTdigitalInputCfg() {
        return new UFPTdigitalInputCfg();
    }

    /**
     * Create an instance of {@link UFPTdigitalOutputCfg }
     * 
     */
    public UFPTdigitalOutputCfg createUFPTdigitalOutputCfg() {
        return new UFPTdigitalOutputCfg();
    }

    /**
     * Create an instance of {@link UFPTnodeObjectCfg }
     * 
     */
    public UFPTnodeObjectCfg createUFPTnodeObjectCfg() {
        return new UFPTnodeObjectCfg();
    }

    /**
     * Create an instance of {@link UFPTpulseCounterCfg }
     * 
     */
    public UFPTpulseCounterCfg createUFPTpulseCounterCfg() {
        return new UFPTpulseCounterCfg();
    }

    /**
     * Create an instance of {@link UFPTrealTimeClockCfg }
     * 
     */
    public UFPTrealTimeClockCfg createUFPTrealTimeClockCfg() {
        return new UFPTrealTimeClockCfg();
    }

    /**
     * Create an instance of {@link UFPTrealTimeClockData }
     * 
     */
    public UFPTrealTimeClockData createUFPTrealTimeClockData() {
        return new UFPTrealTimeClockData();
    }

    /**
     * Create an instance of {@link UFPTrealTimeClockDataDpRef }
     * 
     */
    public UFPTrealTimeClockDataDpRef createUFPTrealTimeClockDataDpRef() {
        return new UFPTrealTimeClockDataDpRef();
    }

    /**
     * Create an instance of {@link UFPTschedulerDpRef }
     * 
     */
    public UFPTschedulerDpRef createUFPTschedulerDpRef() {
        return new UFPTschedulerDpRef();
    }

    /**
     * Create an instance of {@link UFPTschedulerBaseTimeDpRef }
     * 
     */
    public UFPTschedulerBaseTimeDpRef createUFPTschedulerBaseTimeDpRef() {
        return new UFPTschedulerBaseTimeDpRef();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfgEffectivePeriod }
     * 
     */
    public UFPTschedulerCfgEffectivePeriod createUFPTschedulerCfgEffectivePeriod() {
        return new UFPTschedulerCfgEffectivePeriod();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfgEvent }
     * 
     */
    public UFPTschedulerCfgEvent createUFPTschedulerCfgEvent() {
        return new UFPTschedulerCfgEvent();
    }

    /**
     * Create an instance of {@link UFPTschedulerData }
     * 
     */
    public UFPTschedulerData createUFPTschedulerData() {
        return new UFPTschedulerData();
    }

    /**
     * Create an instance of {@link UFPTschedulerCalendarMetaData }
     * 
     */
    public UFPTschedulerCalendarMetaData createUFPTschedulerCalendarMetaData() {
        return new UFPTschedulerCalendarMetaData();
    }

    /**
     * Create an instance of {@link UFPTschedulerCalendarRequestData }
     * 
     */
    public UFPTschedulerCalendarRequestData createUFPTschedulerCalendarRequestData() {
        return new UFPTschedulerCalendarRequestData();
    }

    /**
     * Create an instance of {@link UFPTschedulerRealTimeClockMetaData }
     * 
     */
    public UFPTschedulerRealTimeClockMetaData createUFPTschedulerRealTimeClockMetaData() {
        return new UFPTschedulerRealTimeClockMetaData();
    }

    /**
     * Create an instance of {@link UFPTschedulerRealTimeClockRequestData }
     * 
     */
    public UFPTschedulerRealTimeClockRequestData createUFPTschedulerRealTimeClockRequestData() {
        return new UFPTschedulerRealTimeClockRequestData();
    }

    /**
     * Create an instance of {@link UFPTschedulerMetaData }
     * 
     */
    public UFPTschedulerMetaData createUFPTschedulerMetaData() {
        return new UFPTschedulerMetaData();
    }

    /**
     * Create an instance of {@link UFPTschedulerListSchedulesInvoke }
     * 
     */
    public UFPTschedulerListSchedulesInvoke createUFPTschedulerListSchedulesInvoke() {
        return new UFPTschedulerListSchedulesInvoke();
    }

    /**
     * Create an instance of {@link UFPTschedulerListSchedulesInvokeResponse }
     * 
     */
    public UFPTschedulerListSchedulesInvokeResponse createUFPTschedulerListSchedulesInvokeResponse() {
        return new UFPTschedulerListSchedulesInvokeResponse();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorCfg }
     * 
     */
    public UFPTtypeTranslatorCfg createUFPTtypeTranslatorCfg() {
        return new UFPTtypeTranslatorCfg();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorDpRef }
     * 
     */
    public UFPTtypeTranslatorDpRef createUFPTtypeTranslatorDpRef() {
        return new UFPTtypeTranslatorDpRef();
    }

    /**
     * Create an instance of {@link FileSystemCfg }
     * 
     */
    public FileSystemCfg createFileSystemCfg() {
        return new FileSystemCfg();
    }

    /**
     * Create an instance of {@link FileSystemData }
     * 
     */
    public FileSystemData createFileSystemData() {
        return new FileSystemData();
    }

    /**
     * Create an instance of {@link TemplateManagerSurrogateCfg }
     * 
     */
    public TemplateManagerSurrogateCfg createTemplateManagerSurrogateCfg() {
        return new TemplateManagerSurrogateCfg();
    }

    /**
     * Create an instance of {@link TemplateManagerCfg }
     * 
     */
    public TemplateManagerCfg createTemplateManagerCfg() {
        return new TemplateManagerCfg();
    }

    /**
     * Create an instance of {@link TemplateManagerFILECfg }
     * 
     */
    public TemplateManagerFILECfg createTemplateManagerFILECfg() {
        return new TemplateManagerFILECfg();
    }

    /**
     * Create an instance of {@link TemplateManagerNVTCfg }
     * 
     */
    public TemplateManagerNVTCfg createTemplateManagerNVTCfg() {
        return new TemplateManagerNVTCfg();
    }

    /**
     * Create an instance of {@link TemplateManagerCPTCfg }
     * 
     */
    public TemplateManagerCPTCfg createTemplateManagerCPTCfg() {
        return new TemplateManagerCPTCfg();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgEnum }
     * 
     */
    public TemplateManagerCfgEnum createTemplateManagerCfgEnum() {
        return new TemplateManagerCfgEnum();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgFloat }
     * 
     */
    public TemplateManagerCfgFloat createTemplateManagerCfgFloat() {
        return new TemplateManagerCfgFloat();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgFormatString }
     * 
     */
    public TemplateManagerCfgFormatString createTemplateManagerCfgFormatString() {
        return new TemplateManagerCfgFormatString();
    }

    /**
     * Create an instance of {@link TemplateManagerDataInvoke }
     * 
     */
    public TemplateManagerDataInvoke createTemplateManagerDataInvoke() {
        return new TemplateManagerDataInvoke();
    }

    /**
     * Create an instance of {@link TemplateManagerDataInvokeResponse }
     * 
     */
    public TemplateManagerDataInvokeResponse createTemplateManagerDataInvokeResponse() {
        return new TemplateManagerDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONChannelCfg }
     * 
     */
    public LONChannelCfg createLONChannelCfg() {
        return new LONChannelCfg();
    }

    /**
     * Create an instance of {@link LONDeviceNetworkInterfaceCfg }
     * 
     */
    public LONDeviceNetworkInterfaceCfg createLONDeviceNetworkInterfaceCfg() {
        return new LONDeviceNetworkInterfaceCfg();
    }

    /**
     * Create an instance of {@link LONDeviceRNICfg }
     * 
     */
    public LONDeviceRNICfg createLONDeviceRNICfg() {
        return new LONDeviceRNICfg();
    }

    /**
     * Create an instance of {@link LONDeviceRouterCfg }
     * 
     */
    public LONDeviceRouterCfg createLONDeviceRouterCfg() {
        return new LONDeviceRouterCfg();
    }

    /**
     * Create an instance of {@link LONFbCfg }
     * 
     */
    public LONFbCfg createLONFbCfg() {
        return new LONFbCfg();
    }

    /**
     * Create an instance of {@link LONDpCfg }
     * 
     */
    public LONDpCfg createLONDpCfg() {
        return new LONDpCfg();
    }

    /**
     * Create an instance of {@link LONCpFileCfg }
     * 
     */
    public LONCpFileCfg createLONCpFileCfg() {
        return new LONCpFileCfg();
    }

    /**
     * Create an instance of {@link LONCpDpCfg }
     * 
     */
    public LONCpDpCfg createLONCpDpCfg() {
        return new LONCpDpCfg();
    }

    /**
     * Create an instance of {@link LONNetworkDeviceCommandInvoke }
     * 
     */
    public LONNetworkDeviceCommandInvoke createLONNetworkDeviceCommandInvoke() {
        return new LONNetworkDeviceCommandInvoke();
    }

    /**
     * Create an instance of {@link LONNetworkCommandInvoke }
     * 
     */
    public LONNetworkCommandInvoke createLONNetworkCommandInvoke() {
        return new LONNetworkCommandInvoke();
    }

    /**
     * Create an instance of {@link LONDeviceCommandInvoke }
     * 
     */
    public LONDeviceCommandInvoke createLONDeviceCommandInvoke() {
        return new LONDeviceCommandInvoke();
    }

    /**
     * Create an instance of {@link LONDeviceStatusDataInvokeResponse }
     * 
     */
    public LONDeviceStatusDataInvokeResponse createLONDeviceStatusDataInvokeResponse() {
        return new LONDeviceStatusDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONDevicePowerlineDataInvokeResponse }
     * 
     */
    public LONDevicePowerlineDataInvokeResponse createLONDevicePowerlineDataInvokeResponse() {
        return new LONDevicePowerlineDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONDeviceDataFrequencyInfo }
     * 
     */
    public LONDeviceDataFrequencyInfo createLONDeviceDataFrequencyInfo() {
        return new LONDeviceDataFrequencyInfo();
    }

    /**
     * Create an instance of {@link LONDevicePPNDataInvokeResponse }
     * 
     */
    public LONDevicePPNDataInvokeResponse createLONDevicePPNDataInvokeResponse() {
        return new LONDevicePPNDataInvokeResponse();
    }

    /**
     * Create an instance of {@link LONDeviceEPPNRouteCost }
     * 
     */
    public LONDeviceEPPNRouteCost createLONDeviceEPPNRouteCost() {
        return new LONDeviceEPPNRouteCost();
    }

    /**
     * Create an instance of {@link VirtualNetworkCfg }
     * 
     */
    public VirtualNetworkCfg createVirtualNetworkCfg() {
        return new VirtualNetworkCfg();
    }

    /**
     * Create an instance of {@link VirtualChannelCfg }
     * 
     */
    public VirtualChannelCfg createVirtualChannelCfg() {
        return new VirtualChannelCfg();
    }

    /**
     * Create an instance of {@link VirtualDeviceCfg }
     * 
     */
    public VirtualDeviceCfg createVirtualDeviceCfg() {
        return new VirtualDeviceCfg();
    }

    /**
     * Create an instance of {@link VirtualFbCfg }
     * 
     */
    public VirtualFbCfg createVirtualFbCfg() {
        return new VirtualFbCfg();
    }

    /**
     * Create an instance of {@link VirtualDpCfg }
     * 
     */
    public VirtualDpCfg createVirtualDpCfg() {
        return new VirtualDpCfg();
    }

    /**
     * Create an instance of {@link MODNetworkCfg }
     * 
     */
    public MODNetworkCfg createMODNetworkCfg() {
        return new MODNetworkCfg();
    }

    /**
     * Create an instance of {@link MODChannelCfg }
     * 
     */
    public MODChannelCfg createMODChannelCfg() {
        return new MODChannelCfg();
    }

    /**
     * Create an instance of {@link MODFbCfg }
     * 
     */
    public MODFbCfg createMODFbCfg() {
        return new MODFbCfg();
    }

    /**
     * Create an instance of {@link MODDpCfg }
     * 
     */
    public MODDpCfg createMODDpCfg() {
        return new MODDpCfg();
    }

    /**
     * Create an instance of {@link MBSNetworkCfg }
     * 
     */
    public MBSNetworkCfg createMBSNetworkCfg() {
        return new MBSNetworkCfg();
    }

    /**
     * Create an instance of {@link MBSChannelCfg }
     * 
     */
    public MBSChannelCfg createMBSChannelCfg() {
        return new MBSChannelCfg();
    }

    /**
     * Create an instance of {@link MBSFbCfg }
     * 
     */
    public MBSFbCfg createMBSFbCfg() {
        return new MBSFbCfg();
    }

    /**
     * Create an instance of {@link MBSDpCfg }
     * 
     */
    public MBSDpCfg createMBSDpCfg() {
        return new MBSDpCfg();
    }

    /**
     * Create an instance of {@link MBSDeviceCfg.Address }
     * 
     */
    public MBSDeviceCfg.Address createMBSDeviceCfgAddress() {
        return new MBSDeviceCfg.Address();
    }

    /**
     * Create an instance of {@link MODDeviceCfg.Address }
     * 
     */
    public MODDeviceCfg.Address createMODDeviceCfgAddress() {
        return new MODDeviceCfg.Address();
    }

    /**
     * Create an instance of {@link LONDeviceProxyDataInvokeResponse.ProxyAgent }
     * 
     */
    public LONDeviceProxyDataInvokeResponse.ProxyAgent createLONDeviceProxyDataInvokeResponseProxyAgent() {
        return new LONDeviceProxyDataInvokeResponse.ProxyAgent();
    }

    /**
     * Create an instance of {@link LONDeviceRepeatingDataInvokeResponse.RepeatChain }
     * 
     */
    public LONDeviceRepeatingDataInvokeResponse.RepeatChain createLONDeviceRepeatingDataInvokeResponseRepeatChain() {
        return new LONDeviceRepeatingDataInvokeResponse.RepeatChain();
    }

    /**
     * Create an instance of {@link LONNetworkPPNBlacklistInvoke.Entry }
     * 
     */
    public LONNetworkPPNBlacklistInvoke.Entry createLONNetworkPPNBlacklistInvokeEntry() {
        return new LONNetworkPPNBlacklistInvoke.Entry();
    }

    /**
     * Create an instance of {@link LONNetworkScanCommandInvoke.Command }
     * 
     */
    public LONNetworkScanCommandInvoke.Command createLONNetworkScanCommandInvokeCommand() {
        return new LONNetworkScanCommandInvoke.Command();
    }

    /**
     * Create an instance of {@link LONDeviceCfg.UCPTurlCpFile }
     * 
     */
    public LONDeviceCfg.UCPTurlCpFile createLONDeviceCfgUCPTurlCpFile() {
        return new LONDeviceCfg.UCPTurlCpFile();
    }

    /**
     * Create an instance of {@link LONDeviceCfg.Address }
     * 
     */
    public LONDeviceCfg.Address createLONDeviceCfgAddress() {
        return new LONDeviceCfg.Address();
    }

    /**
     * Create an instance of {@link LONDeviceCfg.Command }
     * 
     */
    public LONDeviceCfg.Command createLONDeviceCfgCommand() {
        return new LONDeviceCfg.Command();
    }

    /**
     * Create an instance of {@link LONNetworkCfg.LnsDatabase }
     * 
     */
    public LONNetworkCfg.LnsDatabase createLONNetworkCfgLnsDatabase() {
        return new LONNetworkCfg.LnsDatabase();
    }

    /**
     * Create an instance of {@link LONNetworkCfg.Domain }
     * 
     */
    public LONNetworkCfg.Domain createLONNetworkCfgDomain() {
        return new LONNetworkCfg.Domain();
    }

    /**
     * Create an instance of {@link DpRef.DataPoint }
     * 
     */
    public DpRef.DataPoint createDpRefDataPoint() {
        return new DpRef.DataPoint();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgStruct.Member }
     * 
     */
    public TemplateManagerCfgStruct.Member createTemplateManagerCfgStructMember() {
        return new TemplateManagerCfgStruct.Member();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgBitfield.Scale }
     * 
     */
    public TemplateManagerCfgBitfield.Scale createTemplateManagerCfgBitfieldScale() {
        return new TemplateManagerCfgBitfield.Scale();
    }

    /**
     * Create an instance of {@link TemplateManagerCfgScalar.Scale }
     * 
     */
    public TemplateManagerCfgScalar.Scale createTemplateManagerCfgScalarScale() {
        return new TemplateManagerCfgScalar.Scale();
    }

    /**
     * Create an instance of {@link TemplateManagerFPTCfg.NV }
     * 
     */
    public TemplateManagerFPTCfg.NV createTemplateManagerFPTCfgNV() {
        return new TemplateManagerFPTCfg.NV();
    }

    /**
     * Create an instance of {@link TemplateManagerFPTCfg.CP }
     * 
     */
    public TemplateManagerFPTCfg.CP createTemplateManagerFPTCfgCP() {
        return new TemplateManagerFPTCfg.CP();
    }

    /**
     * Create an instance of {@link TemplateManagerENUMCfg.Member }
     * 
     */
    public TemplateManagerENUMCfg.Member createTemplateManagerENUMCfgMember() {
        return new TemplateManagerENUMCfg.Member();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorRuleCfg.DataPointFormat }
     * 
     */
    public UFPTtypeTranslatorRuleCfg.DataPointFormat createUFPTtypeTranslatorRuleCfgDataPointFormat() {
        return new UFPTtypeTranslatorRuleCfg.DataPointFormat();
    }

    /**
     * Create an instance of {@link UFPTtypeTranslatorRuleCfg.Case.Rule }
     * 
     */
    public UFPTtypeTranslatorRuleCfg.Case.Rule createUFPTtypeTranslatorRuleCfgCaseRule() {
        return new UFPTtypeTranslatorRuleCfg.Case.Rule();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfg.DateBased.Exception }
     * 
     */
    public UFPTschedulerCfg.DateBased.Exception createUFPTschedulerCfgDateBasedException() {
        return new UFPTschedulerCfg.DateBased.Exception();
    }

    /**
     * Create an instance of {@link UFPTschedulerCfg.DayBased.Weekdays }
     * 
     */
    public UFPTschedulerCfg.DayBased.Weekdays createUFPTschedulerCfgDayBasedWeekdays() {
        return new UFPTschedulerCfg.DayBased.Weekdays();
    }

    /**
     * Create an instance of {@link UFPTcalendarCfg.Exception.Schedule }
     * 
     */
    public UFPTcalendarCfg.Exception.Schedule createUFPTcalendarCfgExceptionSchedule() {
        return new UFPTcalendarCfg.Exception.Schedule();
    }

    /**
     * Create an instance of {@link UFPTcalendarCfg.Exception.Client }
     * 
     */
    public UFPTcalendarCfg.Exception.Client createUFPTcalendarCfgExceptionClient() {
        return new UFPTcalendarCfg.Exception.Client();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierData.ReadData }
     * 
     */
    public UFPTalarmNotifierData.ReadData createUFPTalarmNotifierDataReadData() {
        return new UFPTalarmNotifierData.ReadData();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierInputDpRef.AlarmFlags }
     * 
     */
    public UFPTalarmNotifierInputDpRef.AlarmFlags createUFPTalarmNotifierInputDpRefAlarmFlags() {
        return new UFPTalarmNotifierInputDpRef.AlarmFlags();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierCfg.Mail }
     * 
     */
    public UFPTalarmNotifierCfg.Mail createUFPTalarmNotifierCfgMail() {
        return new UFPTalarmNotifierCfg.Mail();
    }

    /**
     * Create an instance of {@link UFPTalarmNotifierCfg.AlarmDest }
     * 
     */
    public UFPTalarmNotifierCfg.AlarmDest createUFPTalarmNotifierCfgAlarmDest() {
        return new UFPTalarmNotifierCfg.AlarmDest();
    }

    /**
     * Create an instance of {@link EVariant.Data }
     * 
     */
    public EVariant.Data createEVariantData() {
        return new EVariant.Data();
    }

    /**
     * Create an instance of {@link EFault.Faultcode }
     * 
     */
    public EFault.Faultcode createEFaultFaultcode() {
        return new EFault.Faultcode();
    }

}
