//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.coi.ilon.proxyclasses;
