//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateManager_CfgFloat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_CfgFloat"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTbaseType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTminValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTmaxValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_CfgFloat", propOrder = {
    "ucpTbaseType",
    "ucpTminValue",
    "ucpTmaxValue"
})
public class TemplateManagerCfgFloat {

    @XmlElement(name = "UCPTbaseType", required = true)
    protected ELonString ucpTbaseType;
    @XmlElement(name = "UCPTminValue", required = true)
    protected ELonString ucpTminValue;
    @XmlElement(name = "UCPTmaxValue", required = true)
    protected ELonString ucpTmaxValue;

    /**
     * Gets the value of the ucpTbaseType property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTbaseType() {
        return ucpTbaseType;
    }

    /**
     * Sets the value of the ucpTbaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTbaseType(ELonString value) {
        this.ucpTbaseType = value;
    }

    /**
     * Gets the value of the ucpTminValue property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTminValue() {
        return ucpTminValue;
    }

    /**
     * Sets the value of the ucpTminValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTminValue(ELonString value) {
        this.ucpTminValue = value;
    }

    /**
     * Gets the value of the ucpTmaxValue property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTmaxValue() {
        return ucpTmaxValue;
    }

    /**
     * Sets the value of the ucpTmaxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTmaxValue(ELonString value) {
        this.ucpTmaxValue = value;
    }

}
