//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Service configuration native type of the service 'TemplateManager'.
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Cfg"][UCPTfileType="TEMPLATE"]"
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Cfg"][UCPTname="/root/config/software/templateManager/UFPTalarmGenerator.xml"]"
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Cfg"][UCPTfileType="TEMPLATE"][UCPTitemType="DP_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Cfg"][UCPTprogramId="900001012881040C"][UCPTfileType="XIF"]"
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Cfg"][UCPTfileType="XIF"]"
 * 			
 * 
 * <p>Java class for TemplateManager_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_Cfg")
@XmlSeeAlso({
    TemplateManagerFILECfg.class,
    TemplateManagerNVTCfg.class,
    TemplateManagerCPTCfg.class,
    TemplateManagerENUMCfg.class,
    TemplateManagerFPTCfg.class
})
public class TemplateManagerCfg
    extends ItemCfg
{


}
