//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 					Service configuration type of the service 'TemplateManager'.
 * 						Example:  xSelect="//Item[@xsi:type="TemplateManager_ENUM_Cfg"][UCPTprogramId="900001012881040C"][UCPTlanguage="enu"]"
 * 			
 * 
 * <p>Java class for TemplateManager_ENUM_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_ENUM_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}TemplateManager_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Member" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmemberName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTvalue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_ENUM_Cfg", propOrder = {
    "member"
})
public class TemplateManagerENUMCfg
    extends TemplateManagerCfg
{

    @XmlElement(name = "Member")
    protected List<TemplateManagerENUMCfg.Member> member;

    /**
     * Gets the value of the member property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the member property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateManagerENUMCfg.Member }
     * 
     * 
     */
    public List<TemplateManagerENUMCfg.Member> getMember() {
        if (member == null) {
            member = new ArrayList<TemplateManagerENUMCfg.Member>();
        }
        return this.member;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmemberName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTvalue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTdescription",
        "ucpTmemberName",
        "ucpTvalue"
    })
    public static class Member {

        @XmlElement(name = "UCPTdescription")
        protected String ucpTdescription;
        @XmlElement(name = "UCPTmemberName", required = true)
        protected String ucpTmemberName;
        @XmlElement(name = "UCPTvalue")
        protected int ucpTvalue;

        /**
         * Gets the value of the ucpTdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTdescription() {
            return ucpTdescription;
        }

        /**
         * Sets the value of the ucpTdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTdescription(String value) {
            this.ucpTdescription = value;
        }

        /**
         * Gets the value of the ucpTmemberName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTmemberName() {
            return ucpTmemberName;
        }

        /**
         * Sets the value of the ucpTmemberName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTmemberName(String value) {
            this.ucpTmemberName = value;
        }

        /**
         * Gets the value of the ucpTvalue property.
         * 
         */
        public int getUCPTvalue() {
            return ucpTvalue;
        }

        /**
         * Sets the value of the ucpTvalue property.
         * 
         */
        public void setUCPTvalue(int value) {
            this.ucpTvalue = value;
        }

    }

}
