//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This type is a common surrogate for any Item with the 'Item_Cfg'-base.
 * 				The embedded item will be stored as a template in the 'TemplateManager'.
 * 				The storage path (directory + filename) is set in the 'UCPTname'.
 * 			
 * 				Service configuration common type of the service 'TemplateManager'.
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_Surrogate_Cfg"][UCPTname="/root/config/software/templateManager/UFPTalarmGenerator.xml"]"
 * 			
 * 
 * <p>Java class for TemplateManager_Surrogate_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_Surrogate_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmbeddedItemColl" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Item_CfgColl" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_Surrogate_Cfg", propOrder = {
    "embeddedItemColl"
})
public class TemplateManagerSurrogateCfg
    extends ItemCfg
{

    @XmlElement(name = "EmbeddedItemColl")
    protected ItemCfgColl embeddedItemColl;

    /**
     * Gets the value of the embeddedItemColl property.
     * 
     * @return
     *     possible object is
     *     {@link ItemCfgColl }
     *     
     */
    public ItemCfgColl getEmbeddedItemColl() {
        return embeddedItemColl;
    }

    /**
     * Sets the value of the embeddedItemColl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemCfgColl }
     *     
     */
    public void setEmbeddedItemColl(ItemCfgColl value) {
        this.embeddedItemColl = value;
    }

}
