//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 					Service configuration type of the service 'TemplateManager'.
 * 						Example:  xSelect="//Item[@xsi:type="TemplateManager_FPT_Cfg"][UCPTprogramId="900001012881040C"][UCPTlanguage="enu"]"
 * 			
 * 
 * <p>Java class for TemplateManager_FPT_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_FPT_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}TemplateManager_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTshortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTfptKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTinheriting" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *         &lt;element name="UCPTreference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTprincipalName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NV" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmemberIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTmandatory" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTshortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTreference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTminValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmaxValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTdirection" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                   &lt;element name="UCPTserviceType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CP" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmemberIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTmandatory" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTshortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTreference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTminValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmaxValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTdefaultValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTappliesTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTreadOnlyFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTdeviceFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmanufactureFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTobjDisableFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTofflineFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTresetFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTminArraySize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTmaxArraySize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_FPT_Cfg", propOrder = {
    "ucpTshortDescription",
    "ucpTfptKey",
    "ucpTinheriting",
    "ucpTreference",
    "ucpTprincipalName",
    "nv",
    "cp"
})
public class TemplateManagerFPTCfg
    extends TemplateManagerCfg
{

    @XmlElement(name = "UCPTshortDescription")
    protected String ucpTshortDescription;
    @XmlElement(name = "UCPTfptKey", required = true)
    protected String ucpTfptKey;
    @XmlElement(name = "UCPTinheriting")
    protected short ucpTinheriting;
    @XmlElement(name = "UCPTreference")
    protected String ucpTreference;
    @XmlElement(name = "UCPTprincipalName", required = true)
    protected String ucpTprincipalName;
    @XmlElement(name = "NV")
    protected List<TemplateManagerFPTCfg.NV> nv;
    @XmlElement(name = "CP")
    protected List<TemplateManagerFPTCfg.CP> cp;

    /**
     * Gets the value of the ucpTshortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTshortDescription() {
        return ucpTshortDescription;
    }

    /**
     * Sets the value of the ucpTshortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTshortDescription(String value) {
        this.ucpTshortDescription = value;
    }

    /**
     * Gets the value of the ucpTfptKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTfptKey() {
        return ucpTfptKey;
    }

    /**
     * Sets the value of the ucpTfptKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTfptKey(String value) {
        this.ucpTfptKey = value;
    }

    /**
     * Gets the value of the ucpTinheriting property.
     * 
     */
    public short getUCPTinheriting() {
        return ucpTinheriting;
    }

    /**
     * Sets the value of the ucpTinheriting property.
     * 
     */
    public void setUCPTinheriting(short value) {
        this.ucpTinheriting = value;
    }

    /**
     * Gets the value of the ucpTreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTreference() {
        return ucpTreference;
    }

    /**
     * Sets the value of the ucpTreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTreference(String value) {
        this.ucpTreference = value;
    }

    /**
     * Gets the value of the ucpTprincipalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTprincipalName() {
        return ucpTprincipalName;
    }

    /**
     * Sets the value of the ucpTprincipalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTprincipalName(String value) {
        this.ucpTprincipalName = value;
    }

    /**
     * Gets the value of the nv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateManagerFPTCfg.NV }
     * 
     * 
     */
    public List<TemplateManagerFPTCfg.NV> getNV() {
        if (nv == null) {
            nv = new ArrayList<TemplateManagerFPTCfg.NV>();
        }
        return this.nv;
    }

    /**
     * Gets the value of the cp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateManagerFPTCfg.CP }
     * 
     * 
     */
    public List<TemplateManagerFPTCfg.CP> getCP() {
        if (cp == null) {
            cp = new ArrayList<TemplateManagerFPTCfg.CP>();
        }
        return this.cp;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmemberIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTmandatory" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTshortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTreference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTminValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmaxValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *         &lt;element name="UCPTdefaultValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *         &lt;element name="UCPTappliesTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTreadOnlyFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTdeviceFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmanufactureFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTobjDisableFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTofflineFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTresetFlag" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="UCPTminArraySize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmaxArraySize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTindex",
        "ucpTname",
        "ucpTdescription",
        "ucpTmemberIndex",
        "ucpTmandatory",
        "ucpTshortDescription",
        "ucpTreference",
        "ucpTminValue",
        "ucpTmaxValue",
        "ucpTdefaultValue",
        "ucpTappliesTo",
        "ucpTreadOnlyFlag",
        "ucpTdeviceFlag",
        "ucpTmanufactureFlag",
        "ucpTobjDisableFlag",
        "ucpTofflineFlag",
        "ucpTresetFlag",
        "ucpTminArraySize",
        "ucpTmaxArraySize"
    })
    public static class CP {

        @XmlElement(name = "UCPTindex")
        protected int ucpTindex;
        @XmlElement(name = "UCPTname", required = true)
        protected String ucpTname;
        @XmlElement(name = "UCPTdescription")
        protected String ucpTdescription;
        @XmlElement(name = "UCPTmemberIndex")
        protected int ucpTmemberIndex;
        @XmlElement(name = "UCPTmandatory")
        protected short ucpTmandatory;
        @XmlElement(name = "UCPTshortDescription")
        protected String ucpTshortDescription;
        @XmlElement(name = "UCPTreference")
        protected String ucpTreference;
        @XmlElement(name = "UCPTminValue")
        protected ELonString ucpTminValue;
        @XmlElement(name = "UCPTmaxValue")
        protected ELonString ucpTmaxValue;
        @XmlElement(name = "UCPTdefaultValue")
        protected ELonString ucpTdefaultValue;
        @XmlElement(name = "UCPTappliesTo")
        protected String ucpTappliesTo;
        @XmlElement(name = "UCPTreadOnlyFlag")
        protected Short ucpTreadOnlyFlag;
        @XmlElement(name = "UCPTdeviceFlag")
        protected Short ucpTdeviceFlag;
        @XmlElement(name = "UCPTmanufactureFlag")
        protected Short ucpTmanufactureFlag;
        @XmlElement(name = "UCPTobjDisableFlag")
        protected Short ucpTobjDisableFlag;
        @XmlElement(name = "UCPTofflineFlag")
        protected Short ucpTofflineFlag;
        @XmlElement(name = "UCPTresetFlag")
        protected Short ucpTresetFlag;
        @XmlElement(name = "UCPTminArraySize")
        protected Integer ucpTminArraySize;
        @XmlElement(name = "UCPTmaxArraySize")
        protected Integer ucpTmaxArraySize;

        /**
         * Gets the value of the ucpTindex property.
         * 
         */
        public int getUCPTindex() {
            return ucpTindex;
        }

        /**
         * Sets the value of the ucpTindex property.
         * 
         */
        public void setUCPTindex(int value) {
            this.ucpTindex = value;
        }

        /**
         * Gets the value of the ucpTname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTname() {
            return ucpTname;
        }

        /**
         * Sets the value of the ucpTname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTname(String value) {
            this.ucpTname = value;
        }

        /**
         * Gets the value of the ucpTdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTdescription() {
            return ucpTdescription;
        }

        /**
         * Sets the value of the ucpTdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTdescription(String value) {
            this.ucpTdescription = value;
        }

        /**
         * Gets the value of the ucpTmemberIndex property.
         * 
         */
        public int getUCPTmemberIndex() {
            return ucpTmemberIndex;
        }

        /**
         * Sets the value of the ucpTmemberIndex property.
         * 
         */
        public void setUCPTmemberIndex(int value) {
            this.ucpTmemberIndex = value;
        }

        /**
         * Gets the value of the ucpTmandatory property.
         * 
         */
        public short getUCPTmandatory() {
            return ucpTmandatory;
        }

        /**
         * Sets the value of the ucpTmandatory property.
         * 
         */
        public void setUCPTmandatory(short value) {
            this.ucpTmandatory = value;
        }

        /**
         * Gets the value of the ucpTshortDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTshortDescription() {
            return ucpTshortDescription;
        }

        /**
         * Sets the value of the ucpTshortDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTshortDescription(String value) {
            this.ucpTshortDescription = value;
        }

        /**
         * Gets the value of the ucpTreference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTreference() {
            return ucpTreference;
        }

        /**
         * Sets the value of the ucpTreference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTreference(String value) {
            this.ucpTreference = value;
        }

        /**
         * Gets the value of the ucpTminValue property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTminValue() {
            return ucpTminValue;
        }

        /**
         * Sets the value of the ucpTminValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTminValue(ELonString value) {
            this.ucpTminValue = value;
        }

        /**
         * Gets the value of the ucpTmaxValue property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTmaxValue() {
            return ucpTmaxValue;
        }

        /**
         * Sets the value of the ucpTmaxValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTmaxValue(ELonString value) {
            this.ucpTmaxValue = value;
        }

        /**
         * Gets the value of the ucpTdefaultValue property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTdefaultValue() {
            return ucpTdefaultValue;
        }

        /**
         * Sets the value of the ucpTdefaultValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTdefaultValue(ELonString value) {
            this.ucpTdefaultValue = value;
        }

        /**
         * Gets the value of the ucpTappliesTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTappliesTo() {
            return ucpTappliesTo;
        }

        /**
         * Sets the value of the ucpTappliesTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTappliesTo(String value) {
            this.ucpTappliesTo = value;
        }

        /**
         * Gets the value of the ucpTreadOnlyFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTreadOnlyFlag() {
            return ucpTreadOnlyFlag;
        }

        /**
         * Sets the value of the ucpTreadOnlyFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTreadOnlyFlag(Short value) {
            this.ucpTreadOnlyFlag = value;
        }

        /**
         * Gets the value of the ucpTdeviceFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTdeviceFlag() {
            return ucpTdeviceFlag;
        }

        /**
         * Sets the value of the ucpTdeviceFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTdeviceFlag(Short value) {
            this.ucpTdeviceFlag = value;
        }

        /**
         * Gets the value of the ucpTmanufactureFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTmanufactureFlag() {
            return ucpTmanufactureFlag;
        }

        /**
         * Sets the value of the ucpTmanufactureFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTmanufactureFlag(Short value) {
            this.ucpTmanufactureFlag = value;
        }

        /**
         * Gets the value of the ucpTobjDisableFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTobjDisableFlag() {
            return ucpTobjDisableFlag;
        }

        /**
         * Sets the value of the ucpTobjDisableFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTobjDisableFlag(Short value) {
            this.ucpTobjDisableFlag = value;
        }

        /**
         * Gets the value of the ucpTofflineFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTofflineFlag() {
            return ucpTofflineFlag;
        }

        /**
         * Sets the value of the ucpTofflineFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTofflineFlag(Short value) {
            this.ucpTofflineFlag = value;
        }

        /**
         * Gets the value of the ucpTresetFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTresetFlag() {
            return ucpTresetFlag;
        }

        /**
         * Sets the value of the ucpTresetFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTresetFlag(Short value) {
            this.ucpTresetFlag = value;
        }

        /**
         * Gets the value of the ucpTminArraySize property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTminArraySize() {
            return ucpTminArraySize;
        }

        /**
         * Sets the value of the ucpTminArraySize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTminArraySize(Integer value) {
            this.ucpTminArraySize = value;
        }

        /**
         * Gets the value of the ucpTmaxArraySize property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTmaxArraySize() {
            return ucpTmaxArraySize;
        }

        /**
         * Sets the value of the ucpTmaxArraySize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTmaxArraySize(Integer value) {
            this.ucpTmaxArraySize = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmemberIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTmandatory" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTshortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTreference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTminValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *         &lt;element name="UCPTmaxValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
     *         &lt;element name="UCPTdirection" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *         &lt;element name="UCPTserviceType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTindex",
        "ucpTname",
        "ucpTdescription",
        "ucpTmemberIndex",
        "ucpTmandatory",
        "ucpTshortDescription",
        "ucpTreference",
        "ucpTminValue",
        "ucpTmaxValue",
        "ucpTdirection",
        "ucpTserviceType"
    })
    public static class NV {

        @XmlElement(name = "UCPTindex")
        protected int ucpTindex;
        @XmlElement(name = "UCPTname", required = true)
        protected String ucpTname;
        @XmlElement(name = "UCPTdescription")
        protected String ucpTdescription;
        @XmlElement(name = "UCPTmemberIndex")
        protected int ucpTmemberIndex;
        @XmlElement(name = "UCPTmandatory")
        protected short ucpTmandatory;
        @XmlElement(name = "UCPTshortDescription")
        protected String ucpTshortDescription;
        @XmlElement(name = "UCPTreference")
        protected String ucpTreference;
        @XmlElement(name = "UCPTminValue")
        protected ELonString ucpTminValue;
        @XmlElement(name = "UCPTmaxValue")
        protected ELonString ucpTmaxValue;
        @XmlElement(name = "UCPTdirection", required = true)
        protected ELonString ucpTdirection;
        @XmlElement(name = "UCPTserviceType", required = true)
        protected ELonString ucpTserviceType;

        /**
         * Gets the value of the ucpTindex property.
         * 
         */
        public int getUCPTindex() {
            return ucpTindex;
        }

        /**
         * Sets the value of the ucpTindex property.
         * 
         */
        public void setUCPTindex(int value) {
            this.ucpTindex = value;
        }

        /**
         * Gets the value of the ucpTname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTname() {
            return ucpTname;
        }

        /**
         * Sets the value of the ucpTname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTname(String value) {
            this.ucpTname = value;
        }

        /**
         * Gets the value of the ucpTdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTdescription() {
            return ucpTdescription;
        }

        /**
         * Sets the value of the ucpTdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTdescription(String value) {
            this.ucpTdescription = value;
        }

        /**
         * Gets the value of the ucpTmemberIndex property.
         * 
         */
        public int getUCPTmemberIndex() {
            return ucpTmemberIndex;
        }

        /**
         * Sets the value of the ucpTmemberIndex property.
         * 
         */
        public void setUCPTmemberIndex(int value) {
            this.ucpTmemberIndex = value;
        }

        /**
         * Gets the value of the ucpTmandatory property.
         * 
         */
        public short getUCPTmandatory() {
            return ucpTmandatory;
        }

        /**
         * Sets the value of the ucpTmandatory property.
         * 
         */
        public void setUCPTmandatory(short value) {
            this.ucpTmandatory = value;
        }

        /**
         * Gets the value of the ucpTshortDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTshortDescription() {
            return ucpTshortDescription;
        }

        /**
         * Sets the value of the ucpTshortDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTshortDescription(String value) {
            this.ucpTshortDescription = value;
        }

        /**
         * Gets the value of the ucpTreference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTreference() {
            return ucpTreference;
        }

        /**
         * Sets the value of the ucpTreference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTreference(String value) {
            this.ucpTreference = value;
        }

        /**
         * Gets the value of the ucpTminValue property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTminValue() {
            return ucpTminValue;
        }

        /**
         * Sets the value of the ucpTminValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTminValue(ELonString value) {
            this.ucpTminValue = value;
        }

        /**
         * Gets the value of the ucpTmaxValue property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTmaxValue() {
            return ucpTmaxValue;
        }

        /**
         * Sets the value of the ucpTmaxValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTmaxValue(ELonString value) {
            this.ucpTmaxValue = value;
        }

        /**
         * Gets the value of the ucpTdirection property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTdirection() {
            return ucpTdirection;
        }

        /**
         * Sets the value of the ucpTdirection property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTdirection(ELonString value) {
            this.ucpTdirection = value;
        }

        /**
         * Gets the value of the ucpTserviceType property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTserviceType() {
            return ucpTserviceType;
        }

        /**
         * Sets the value of the ucpTserviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTserviceType(ELonString value) {
            this.ucpTserviceType = value;
        }

    }

}
