//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateManager_CfgFormatString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_CfgFormatString"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTformatDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTformatSpecifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_CfgFormatString", propOrder = {
    "ucpTformatDescription",
    "ucpTformatSpecifier"
})
public class TemplateManagerCfgFormatString {

    @XmlElement(name = "UCPTformatDescription", required = true)
    protected String ucpTformatDescription;
    @XmlElement(name = "UCPTformatSpecifier", required = true)
    protected String ucpTformatSpecifier;

    /**
     * Gets the value of the ucpTformatDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTformatDescription() {
        return ucpTformatDescription;
    }

    /**
     * Sets the value of the ucpTformatDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTformatDescription(String value) {
        this.ucpTformatDescription = value;
    }

    /**
     * Gets the value of the ucpTformatSpecifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTformatSpecifier() {
        return ucpTformatSpecifier;
    }

    /**
     * Sets the value of the ucpTformatSpecifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTformatSpecifier(String value) {
        this.ucpTformatSpecifier = value;
    }

}
