//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Service configuration type of the service 'TemplateManager'.
 * 					Example:  xSelect="//Item[@xsi:type="TemplateManager_FILE_Cfg"][UCPTprogramId="900001012881040C"]"
 * 			
 * 
 * <p>Java class for TemplateManager_FILE_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateManager_FILE_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}TemplateManager_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTresourceFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTdataVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTformatVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTcreator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateManager_FILE_Cfg", propOrder = {
    "ucpTresourceFile",
    "ucpTdataVersion",
    "ucpTformatVersion",
    "ucpTcreator"
})
public class TemplateManagerFILECfg
    extends TemplateManagerCfg
{

    @XmlElement(name = "UCPTresourceFile")
    protected String ucpTresourceFile;
    @XmlElement(name = "UCPTdataVersion")
    protected String ucpTdataVersion;
    @XmlElement(name = "UCPTformatVersion")
    protected String ucpTformatVersion;
    @XmlElement(name = "UCPTcreator")
    protected String ucpTcreator;

    /**
     * Gets the value of the ucpTresourceFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTresourceFile() {
        return ucpTresourceFile;
    }

    /**
     * Sets the value of the ucpTresourceFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTresourceFile(String value) {
        this.ucpTresourceFile = value;
    }

    /**
     * Gets the value of the ucpTdataVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTdataVersion() {
        return ucpTdataVersion;
    }

    /**
     * Sets the value of the ucpTdataVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTdataVersion(String value) {
        this.ucpTdataVersion = value;
    }

    /**
     * Gets the value of the ucpTformatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTformatVersion() {
        return ucpTformatVersion;
    }

    /**
     * Sets the value of the ucpTformatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTformatVersion(String value) {
        this.ucpTformatVersion = value;
    }

    /**
     * Gets the value of the ucpTcreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTcreator() {
        return ucpTcreator;
    }

    /**
     * Sets the value of the ucpTcreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTcreator(String value) {
        this.ucpTcreator = value;
    }

}
