//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Generalized data type of the 'UFPTalarmNotifier'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTalarmNotifier_Data"][UCPTpointName="Net/LON/BAS/Alarm Notifier 1/nviInput"]"
 * 					Example:  xSelect="//Item[@xsi:type="UFPTalarmNotifier_Data"][UCPTalarmTime>="2007-01-15T15:30:21Z"][position()<=60][UCPTalarmLog="SUMMARY"]"
 * 			
 * 
 * <p>Java class for UFPTalarmNotifier_Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTalarmNotifier_Data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Dp_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTalarmNotifierName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTalarmTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="UCPTuserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTstatus" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="ReadData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTalarmText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTalarmPriority2" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Priority"/&gt;
 *                   &lt;element name="UCPTalarmGroup" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="UCPTalarmType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTalarmNotifier_Data", propOrder = {
    "ucpTalarmNotifierName",
    "ucpTalarmTime",
    "ucpTuserName",
    "ucpTstatus",
    "readData"
})
public class UFPTalarmNotifierData
    extends DpData
{

    @XmlElement(name = "UCPTalarmNotifierName", required = true)
    protected String ucpTalarmNotifierName;
    @XmlElement(name = "UCPTalarmTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ucpTalarmTime;
    @XmlElement(name = "UCPTuserName")
    protected String ucpTuserName;
    @XmlElement(name = "UCPTstatus")
    protected ELonString ucpTstatus;
    @XmlElement(name = "ReadData")
    protected UFPTalarmNotifierData.ReadData readData;

    /**
     * Gets the value of the ucpTalarmNotifierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTalarmNotifierName() {
        return ucpTalarmNotifierName;
    }

    /**
     * Sets the value of the ucpTalarmNotifierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTalarmNotifierName(String value) {
        this.ucpTalarmNotifierName = value;
    }

    /**
     * Gets the value of the ucpTalarmTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUCPTalarmTime() {
        return ucpTalarmTime;
    }

    /**
     * Sets the value of the ucpTalarmTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUCPTalarmTime(XMLGregorianCalendar value) {
        this.ucpTalarmTime = value;
    }

    /**
     * Gets the value of the ucpTuserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTuserName() {
        return ucpTuserName;
    }

    /**
     * Sets the value of the ucpTuserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTuserName(String value) {
        this.ucpTuserName = value;
    }

    /**
     * Gets the value of the ucpTstatus property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTstatus() {
        return ucpTstatus;
    }

    /**
     * Sets the value of the ucpTstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTstatus(ELonString value) {
        this.ucpTstatus = value;
    }

    /**
     * Gets the value of the readData property.
     * 
     * @return
     *     possible object is
     *     {@link UFPTalarmNotifierData.ReadData }
     *     
     */
    public UFPTalarmNotifierData.ReadData getReadData() {
        return readData;
    }

    /**
     * Sets the value of the readData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UFPTalarmNotifierData.ReadData }
     *     
     */
    public void setReadData(UFPTalarmNotifierData.ReadData value) {
        this.readData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTalarmText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTalarmPriority2" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Priority"/&gt;
     *         &lt;element name="UCPTalarmGroup" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="UCPTalarmType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTalarmText",
        "ucpTalarmPriority2",
        "ucpTalarmGroup",
        "ucpTalarmType"
    })
    public static class ReadData {

        @XmlElement(name = "UCPTalarmText", required = true)
        protected String ucpTalarmText;
        @XmlElement(name = "UCPTalarmPriority2")
        protected int ucpTalarmPriority2;
        @XmlElement(name = "UCPTalarmGroup")
        protected int ucpTalarmGroup;
        @XmlElement(name = "UCPTalarmType", required = true)
        protected ELonString ucpTalarmType;

        /**
         * Gets the value of the ucpTalarmText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTalarmText() {
            return ucpTalarmText;
        }

        /**
         * Sets the value of the ucpTalarmText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTalarmText(String value) {
            this.ucpTalarmText = value;
        }

        /**
         * Gets the value of the ucpTalarmPriority2 property.
         * 
         */
        public int getUCPTalarmPriority2() {
            return ucpTalarmPriority2;
        }

        /**
         * Sets the value of the ucpTalarmPriority2 property.
         * 
         */
        public void setUCPTalarmPriority2(int value) {
            this.ucpTalarmPriority2 = value;
        }

        /**
         * Gets the value of the ucpTalarmGroup property.
         * 
         */
        public int getUCPTalarmGroup() {
            return ucpTalarmGroup;
        }

        /**
         * Sets the value of the ucpTalarmGroup property.
         * 
         */
        public void setUCPTalarmGroup(int value) {
            this.ucpTalarmGroup = value;
        }

        /**
         * Gets the value of the ucpTalarmType property.
         * 
         * @return
         *     possible object is
         *     {@link ELonString }
         *     
         */
        public ELonString getUCPTalarmType() {
            return ucpTalarmType;
        }

        /**
         * Sets the value of the ucpTalarmType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ELonString }
         *     
         */
        public void setUCPTalarmType(ELonString value) {
            this.ucpTalarmType = value;
        }

    }

}
