//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized data type of the 'UFPTdataLogger'.
 * 					Example:   xSelect="//Item[@xsi:type="UFPTdataLogger_Data"][UCPTlastUpdate>="2007-01-15T15:30:21Z"][position()<50]"
 * 					Example:   xSelect="//Item[@xsi:type="UFPTdataLogger_Data"][UCPTpointName="Net/LON/BAS/Data Logger 1/nviInput"][UCPTlastUpdate>="2007-01-15T15:30:21Z"][position()<50]"
 * 			
 * 
 * <p>Java class for UFPTdataLogger_Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTdataLogger_Data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Dp_Data"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTdataLogger_Data")
public class UFPTdataLoggerData
    extends DpData
{


}
