//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized configuration type of the 'UFPTcalendar'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTcalendar_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="UFPTcalendar_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for UFPTcalendar_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTcalendar_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ScheduleEffectivePeriod" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTscheduler_CfgEffectivePeriod"/&gt;
 *         &lt;element name="Exception" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTexceptionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTaliasName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTtemporary" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
 *                   &lt;element name="Schedule" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="StartDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
 *                             &lt;element name="EndDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
 *                             &lt;element name="UCPTschedDay" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                             &lt;element name="UCPTschedMonth" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="UCPTmaxClient" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="Client" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="UCPTservicePath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTcalendar_Cfg", propOrder = {
    "scheduleEffectivePeriod",
    "exception"
})
public class UFPTcalendarCfg
    extends FbCfg
{

    @XmlElement(name = "ScheduleEffectivePeriod", required = true)
    protected UFPTschedulerCfgEffectivePeriod scheduleEffectivePeriod;
    @XmlElement(name = "Exception")
    protected List<UFPTcalendarCfg.Exception> exception;

    /**
     * Gets the value of the scheduleEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link UFPTschedulerCfgEffectivePeriod }
     *     
     */
    public UFPTschedulerCfgEffectivePeriod getScheduleEffectivePeriod() {
        return scheduleEffectivePeriod;
    }

    /**
     * Sets the value of the scheduleEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link UFPTschedulerCfgEffectivePeriod }
     *     
     */
    public void setScheduleEffectivePeriod(UFPTschedulerCfgEffectivePeriod value) {
        this.scheduleEffectivePeriod = value;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UFPTcalendarCfg.Exception }
     * 
     * 
     */
    public List<UFPTcalendarCfg.Exception> getException() {
        if (exception == null) {
            exception = new ArrayList<UFPTcalendarCfg.Exception>();
        }
        return this.exception;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTexceptionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTaliasName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTtemporary" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag" minOccurs="0"/&gt;
     *         &lt;element name="Schedule" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="StartDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
     *                   &lt;element name="EndDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
     *                   &lt;element name="UCPTschedDay" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *                   &lt;element name="UCPTschedMonth" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="UCPTmaxClient" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="Client" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="UCPTservicePath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTindex",
        "ucpTexceptionName",
        "ucpTaliasName",
        "ucpTtemporary",
        "schedule",
        "ucpTmaxClient",
        "client"
    })
    public static class Exception {

        @XmlElement(name = "UCPTindex")
        protected Integer ucpTindex;
        @XmlElement(name = "UCPTexceptionName", required = true)
        protected String ucpTexceptionName;
        @XmlElement(name = "UCPTaliasName")
        protected String ucpTaliasName;
        @XmlElement(name = "UCPTtemporary")
        protected Short ucpTtemporary;
        @XmlElement(name = "Schedule")
        protected List<UFPTcalendarCfg.Exception.Schedule> schedule;
        @XmlElement(name = "UCPTmaxClient")
        protected Integer ucpTmaxClient;
        @XmlElement(name = "Client")
        protected List<UFPTcalendarCfg.Exception.Client> client;

        /**
         * Gets the value of the ucpTindex property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTindex() {
            return ucpTindex;
        }

        /**
         * Sets the value of the ucpTindex property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTindex(Integer value) {
            this.ucpTindex = value;
        }

        /**
         * Gets the value of the ucpTexceptionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTexceptionName() {
            return ucpTexceptionName;
        }

        /**
         * Sets the value of the ucpTexceptionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTexceptionName(String value) {
            this.ucpTexceptionName = value;
        }

        /**
         * Gets the value of the ucpTaliasName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTaliasName() {
            return ucpTaliasName;
        }

        /**
         * Sets the value of the ucpTaliasName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTaliasName(String value) {
            this.ucpTaliasName = value;
        }

        /**
         * Gets the value of the ucpTtemporary property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUCPTtemporary() {
            return ucpTtemporary;
        }

        /**
         * Sets the value of the ucpTtemporary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUCPTtemporary(Short value) {
            this.ucpTtemporary = value;
        }

        /**
         * Gets the value of the schedule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the schedule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSchedule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UFPTcalendarCfg.Exception.Schedule }
         * 
         * 
         */
        public List<UFPTcalendarCfg.Exception.Schedule> getSchedule() {
            if (schedule == null) {
                schedule = new ArrayList<UFPTcalendarCfg.Exception.Schedule>();
            }
            return this.schedule;
        }

        /**
         * Gets the value of the ucpTmaxClient property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTmaxClient() {
            return ucpTmaxClient;
        }

        /**
         * Sets the value of the ucpTmaxClient property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTmaxClient(Integer value) {
            this.ucpTmaxClient = value;
        }

        /**
         * Gets the value of the client property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the client property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClient().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UFPTcalendarCfg.Exception.Client }
         * 
         * 
         */
        public List<UFPTcalendarCfg.Exception.Client> getClient() {
            if (client == null) {
                client = new ArrayList<UFPTcalendarCfg.Exception.Client>();
            }
            return this.client;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="UCPTname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="UCPTservicePath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ucpTname",
            "ucpTservicePath"
        })
        public static class Client {

            @XmlElement(name = "UCPTname", required = true)
            protected String ucpTname;
            @XmlElement(name = "UCPTservicePath")
            protected EPath ucpTservicePath;

            /**
             * Gets the value of the ucpTname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUCPTname() {
                return ucpTname;
            }

            /**
             * Sets the value of the ucpTname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUCPTname(String value) {
                this.ucpTname = value;
            }

            /**
             * Gets the value of the ucpTservicePath property.
             * 
             * @return
             *     possible object is
             *     {@link EPath }
             *     
             */
            public EPath getUCPTservicePath() {
                return ucpTservicePath;
            }

            /**
             * Sets the value of the ucpTservicePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link EPath }
             *     
             */
            public void setUCPTservicePath(EPath value) {
                this.ucpTservicePath = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="StartDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
         *         &lt;element name="EndDate" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTcalendar_CfgESDate"/&gt;
         *         &lt;element name="UCPTschedDay" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
         *         &lt;element name="UCPTschedMonth" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startDate",
            "endDate",
            "ucpTschedDay",
            "ucpTschedMonth"
        })
        public static class Schedule {

            @XmlElement(name = "StartDate", required = true)
            protected UFPTcalendarCfgESDate startDate;
            @XmlElement(name = "EndDate", required = true)
            protected UFPTcalendarCfgESDate endDate;
            @XmlElement(name = "UCPTschedDay", required = true)
            protected ELonString ucpTschedDay;
            @XmlElement(name = "UCPTschedMonth", required = true)
            protected ELonString ucpTschedMonth;

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link UFPTcalendarCfgESDate }
             *     
             */
            public UFPTcalendarCfgESDate getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link UFPTcalendarCfgESDate }
             *     
             */
            public void setStartDate(UFPTcalendarCfgESDate value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link UFPTcalendarCfgESDate }
             *     
             */
            public UFPTcalendarCfgESDate getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link UFPTcalendarCfgESDate }
             *     
             */
            public void setEndDate(UFPTcalendarCfgESDate value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the ucpTschedDay property.
             * 
             * @return
             *     possible object is
             *     {@link ELonString }
             *     
             */
            public ELonString getUCPTschedDay() {
                return ucpTschedDay;
            }

            /**
             * Sets the value of the ucpTschedDay property.
             * 
             * @param value
             *     allowed object is
             *     {@link ELonString }
             *     
             */
            public void setUCPTschedDay(ELonString value) {
                this.ucpTschedDay = value;
            }

            /**
             * Gets the value of the ucpTschedMonth property.
             * 
             * @return
             *     possible object is
             *     {@link ELonString }
             *     
             */
            public ELonString getUCPTschedMonth() {
                return ucpTschedMonth;
            }

            /**
             * Sets the value of the ucpTschedMonth property.
             * 
             * @param value
             *     allowed object is
             *     {@link ELonString }
             *     
             */
            public void setUCPTschedMonth(ELonString value) {
                this.ucpTschedMonth = value;
            }

        }

    }

}
