//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized configuration type of the 'UFPTalarmNotifier'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTalarmNotifier_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="UFPTalarmNotifier_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for UFPTalarmNotifier_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTalarmNotifier_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SCPTdelayTime" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="UCPTsumLogSize" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="UCPThistLogSize" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="UCPTlogFormat" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTsumLogFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPThistLogFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTemailAggregTime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Mail" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTnickName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTemailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTemailFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="UCPTemailSubject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTemailAttachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ActiveAlarm" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PassiveAlarm" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AlarmDest" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="UCPTenablePath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
 *                   &lt;element name="ActiveDest" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarmDestination" minOccurs="0"/&gt;
 *                   &lt;element name="PassiveDest" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarmDestination" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTalarmNotifier_Cfg", propOrder = {
    "scpTdelayTime",
    "ucpTsumLogSize",
    "ucpThistLogSize",
    "ucpTlogFormat",
    "ucpTsumLogFileName",
    "ucpThistLogFileName",
    "ucpTemailAggregTime",
    "mail",
    "activeAlarm",
    "passiveAlarm",
    "alarmDest"
})
public class UFPTalarmNotifierCfg
    extends FbCfg
{

    @XmlElement(name = "SCPTdelayTime")
    protected Double scpTdelayTime;
    @XmlElement(name = "UCPTsumLogSize")
    protected float ucpTsumLogSize;
    @XmlElement(name = "UCPThistLogSize")
    protected float ucpThistLogSize;
    @XmlElement(name = "UCPTlogFormat")
    protected ELonString ucpTlogFormat;
    @XmlElement(name = "UCPTsumLogFileName", required = true)
    protected String ucpTsumLogFileName;
    @XmlElement(name = "UCPThistLogFileName", required = true)
    protected String ucpThistLogFileName;
    @XmlElement(name = "UCPTemailAggregTime")
    protected Integer ucpTemailAggregTime;
    @XmlElement(name = "Mail")
    protected List<UFPTalarmNotifierCfg.Mail> mail;
    @XmlElement(name = "ActiveAlarm")
    protected List<UFPTalarmNotifierCfgAlarm> activeAlarm;
    @XmlElement(name = "PassiveAlarm")
    protected List<UFPTalarmNotifierCfgAlarm> passiveAlarm;
    @XmlElement(name = "AlarmDest")
    protected List<UFPTalarmNotifierCfg.AlarmDest> alarmDest;

    /**
     * Gets the value of the scpTdelayTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSCPTdelayTime() {
        return scpTdelayTime;
    }

    /**
     * Sets the value of the scpTdelayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSCPTdelayTime(Double value) {
        this.scpTdelayTime = value;
    }

    /**
     * Gets the value of the ucpTsumLogSize property.
     * 
     */
    public float getUCPTsumLogSize() {
        return ucpTsumLogSize;
    }

    /**
     * Sets the value of the ucpTsumLogSize property.
     * 
     */
    public void setUCPTsumLogSize(float value) {
        this.ucpTsumLogSize = value;
    }

    /**
     * Gets the value of the ucpThistLogSize property.
     * 
     */
    public float getUCPThistLogSize() {
        return ucpThistLogSize;
    }

    /**
     * Sets the value of the ucpThistLogSize property.
     * 
     */
    public void setUCPThistLogSize(float value) {
        this.ucpThistLogSize = value;
    }

    /**
     * Gets the value of the ucpTlogFormat property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTlogFormat() {
        return ucpTlogFormat;
    }

    /**
     * Sets the value of the ucpTlogFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTlogFormat(ELonString value) {
        this.ucpTlogFormat = value;
    }

    /**
     * Gets the value of the ucpTsumLogFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTsumLogFileName() {
        return ucpTsumLogFileName;
    }

    /**
     * Sets the value of the ucpTsumLogFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTsumLogFileName(String value) {
        this.ucpTsumLogFileName = value;
    }

    /**
     * Gets the value of the ucpThistLogFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPThistLogFileName() {
        return ucpThistLogFileName;
    }

    /**
     * Sets the value of the ucpThistLogFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPThistLogFileName(String value) {
        this.ucpThistLogFileName = value;
    }

    /**
     * Gets the value of the ucpTemailAggregTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTemailAggregTime() {
        return ucpTemailAggregTime;
    }

    /**
     * Sets the value of the ucpTemailAggregTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTemailAggregTime(Integer value) {
        this.ucpTemailAggregTime = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UFPTalarmNotifierCfg.Mail }
     * 
     * 
     */
    public List<UFPTalarmNotifierCfg.Mail> getMail() {
        if (mail == null) {
            mail = new ArrayList<UFPTalarmNotifierCfg.Mail>();
        }
        return this.mail;
    }

    /**
     * Gets the value of the activeAlarm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activeAlarm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActiveAlarm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UFPTalarmNotifierCfgAlarm }
     * 
     * 
     */
    public List<UFPTalarmNotifierCfgAlarm> getActiveAlarm() {
        if (activeAlarm == null) {
            activeAlarm = new ArrayList<UFPTalarmNotifierCfgAlarm>();
        }
        return this.activeAlarm;
    }

    /**
     * Gets the value of the passiveAlarm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passiveAlarm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassiveAlarm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UFPTalarmNotifierCfgAlarm }
     * 
     * 
     */
    public List<UFPTalarmNotifierCfgAlarm> getPassiveAlarm() {
        if (passiveAlarm == null) {
            passiveAlarm = new ArrayList<UFPTalarmNotifierCfgAlarm>();
        }
        return this.passiveAlarm;
    }

    /**
     * Gets the value of the alarmDest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alarmDest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlarmDest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UFPTalarmNotifierCfg.AlarmDest }
     * 
     * 
     */
    public List<UFPTalarmNotifierCfg.AlarmDest> getAlarmDest() {
        if (alarmDest == null) {
            alarmDest = new ArrayList<UFPTalarmNotifierCfg.AlarmDest>();
        }
        return this.alarmDest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTenablePath" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Path" minOccurs="0"/&gt;
     *         &lt;element name="ActiveDest" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarmDestination" minOccurs="0"/&gt;
     *         &lt;element name="PassiveDest" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}UFPTalarmNotifier_CfgAlarmDestination" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTindex",
        "ucpTenablePath",
        "activeDest",
        "passiveDest"
    })
    public static class AlarmDest {

        @XmlElement(name = "UCPTindex")
        protected Integer ucpTindex;
        @XmlElement(name = "UCPTenablePath")
        protected EPath ucpTenablePath;
        @XmlElement(name = "ActiveDest")
        protected UFPTalarmNotifierCfgAlarmDestination activeDest;
        @XmlElement(name = "PassiveDest")
        protected UFPTalarmNotifierCfgAlarmDestination passiveDest;

        /**
         * Gets the value of the ucpTindex property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTindex() {
            return ucpTindex;
        }

        /**
         * Sets the value of the ucpTindex property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTindex(Integer value) {
            this.ucpTindex = value;
        }

        /**
         * Gets the value of the ucpTenablePath property.
         * 
         * @return
         *     possible object is
         *     {@link EPath }
         *     
         */
        public EPath getUCPTenablePath() {
            return ucpTenablePath;
        }

        /**
         * Sets the value of the ucpTenablePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link EPath }
         *     
         */
        public void setUCPTenablePath(EPath value) {
            this.ucpTenablePath = value;
        }

        /**
         * Gets the value of the activeDest property.
         * 
         * @return
         *     possible object is
         *     {@link UFPTalarmNotifierCfgAlarmDestination }
         *     
         */
        public UFPTalarmNotifierCfgAlarmDestination getActiveDest() {
            return activeDest;
        }

        /**
         * Sets the value of the activeDest property.
         * 
         * @param value
         *     allowed object is
         *     {@link UFPTalarmNotifierCfgAlarmDestination }
         *     
         */
        public void setActiveDest(UFPTalarmNotifierCfgAlarmDestination value) {
            this.activeDest = value;
        }

        /**
         * Gets the value of the passiveDest property.
         * 
         * @return
         *     possible object is
         *     {@link UFPTalarmNotifierCfgAlarmDestination }
         *     
         */
        public UFPTalarmNotifierCfgAlarmDestination getPassiveDest() {
            return passiveDest;
        }

        /**
         * Sets the value of the passiveDest property.
         * 
         * @param value
         *     allowed object is
         *     {@link UFPTalarmNotifierCfgAlarmDestination }
         *     
         */
        public void setPassiveDest(UFPTalarmNotifierCfgAlarmDestination value) {
            this.passiveDest = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTindex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="UCPTnickName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTemailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTemailFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="UCPTemailSubject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="UCPTemailAttachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTindex",
        "ucpTnickName",
        "ucpTemailAddress",
        "ucpTemailFormat",
        "ucpTemailSubject",
        "ucpTemailAttachment"
    })
    public static class Mail {

        @XmlElement(name = "UCPTindex")
        protected Integer ucpTindex;
        @XmlElement(name = "UCPTnickName")
        protected String ucpTnickName;
        @XmlElement(name = "UCPTemailAddress", required = true)
        protected String ucpTemailAddress;
        @XmlElement(name = "UCPTemailFormat", required = true)
        protected String ucpTemailFormat;
        @XmlElement(name = "UCPTemailSubject")
        protected String ucpTemailSubject;
        @XmlElement(name = "UCPTemailAttachment")
        protected String ucpTemailAttachment;

        /**
         * Gets the value of the ucpTindex property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUCPTindex() {
            return ucpTindex;
        }

        /**
         * Sets the value of the ucpTindex property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUCPTindex(Integer value) {
            this.ucpTindex = value;
        }

        /**
         * Gets the value of the ucpTnickName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTnickName() {
            return ucpTnickName;
        }

        /**
         * Sets the value of the ucpTnickName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTnickName(String value) {
            this.ucpTnickName = value;
        }

        /**
         * Gets the value of the ucpTemailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTemailAddress() {
            return ucpTemailAddress;
        }

        /**
         * Sets the value of the ucpTemailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTemailAddress(String value) {
            this.ucpTemailAddress = value;
        }

        /**
         * Gets the value of the ucpTemailFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTemailFormat() {
            return ucpTemailFormat;
        }

        /**
         * Sets the value of the ucpTemailFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTemailFormat(String value) {
            this.ucpTemailFormat = value;
        }

        /**
         * Gets the value of the ucpTemailSubject property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTemailSubject() {
            return ucpTemailSubject;
        }

        /**
         * Sets the value of the ucpTemailSubject property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTemailSubject(String value) {
            this.ucpTemailSubject = value;
        }

        /**
         * Gets the value of the ucpTemailAttachment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUCPTemailAttachment() {
            return ucpTemailAttachment;
        }

        /**
         * Sets the value of the ucpTemailAttachment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUCPTemailAttachment(String value) {
            this.ucpTemailAttachment = value;
        }

    }

}
