//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for UFPTcalendar_CfgESDate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTcalendar_CfgESDate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTdate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="UCPTyearMask" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTmonthMask" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTdayMask" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTcalendar_CfgESDate", propOrder = {
    "ucpTdate",
    "ucpTyearMask",
    "ucpTmonthMask",
    "ucpTdayMask"
})
public class UFPTcalendarCfgESDate {

    @XmlElement(name = "UCPTdate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ucpTdate;
    @XmlElement(name = "UCPTyearMask")
    protected ELonString ucpTyearMask;
    @XmlElement(name = "UCPTmonthMask")
    protected ELonString ucpTmonthMask;
    @XmlElement(name = "UCPTdayMask")
    protected ELonString ucpTdayMask;

    /**
     * Gets the value of the ucpTdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUCPTdate() {
        return ucpTdate;
    }

    /**
     * Sets the value of the ucpTdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUCPTdate(XMLGregorianCalendar value) {
        this.ucpTdate = value;
    }

    /**
     * Gets the value of the ucpTyearMask property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTyearMask() {
        return ucpTyearMask;
    }

    /**
     * Sets the value of the ucpTyearMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTyearMask(ELonString value) {
        this.ucpTyearMask = value;
    }

    /**
     * Gets the value of the ucpTmonthMask property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTmonthMask() {
        return ucpTmonthMask;
    }

    /**
     * Sets the value of the ucpTmonthMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTmonthMask(ELonString value) {
        this.ucpTmonthMask = value;
    }

    /**
     * Gets the value of the ucpTdayMask property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTdayMask() {
        return ucpTdayMask;
    }

    /**
     * Sets the value of the ucpTdayMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTdayMask(ELonString value) {
        this.ucpTdayMask = value;
    }

}
