//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Generalized data type of the 'UFPTscheduler'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTscheduler_Data"][UCPTname="Net/LON/BAS/Scheduler 1"][UCPTeventFilter="EF_SCHEDULE"][position()<10]"
 * 			
 * 
 * <p>Java class for UFPTscheduler_Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTscheduler_Data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Dp_Data"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTeventType" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTeventSource" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UCPTexceptionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UCPTeventInfo" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTbaseTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTscheduler_Data", propOrder = {
    "ucpTeventType",
    "ucpTeventSource",
    "ucpTexceptionName",
    "ucpTeventInfo",
    "ucpTbaseTime"
})
public class UFPTschedulerData
    extends DpData
{

    @XmlElement(name = "UCPTeventType", required = true)
    protected ELonString ucpTeventType;
    @XmlElement(name = "UCPTeventSource", required = true)
    protected String ucpTeventSource;
    @XmlElement(name = "UCPTexceptionName")
    protected String ucpTexceptionName;
    @XmlElement(name = "UCPTeventInfo", required = true)
    protected ELonString ucpTeventInfo;
    @XmlElement(name = "UCPTbaseTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar ucpTbaseTime;

    /**
     * Gets the value of the ucpTeventType property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTeventType() {
        return ucpTeventType;
    }

    /**
     * Sets the value of the ucpTeventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTeventType(ELonString value) {
        this.ucpTeventType = value;
    }

    /**
     * Gets the value of the ucpTeventSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTeventSource() {
        return ucpTeventSource;
    }

    /**
     * Sets the value of the ucpTeventSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTeventSource(String value) {
        this.ucpTeventSource = value;
    }

    /**
     * Gets the value of the ucpTexceptionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTexceptionName() {
        return ucpTexceptionName;
    }

    /**
     * Sets the value of the ucpTexceptionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTexceptionName(String value) {
        this.ucpTexceptionName = value;
    }

    /**
     * Gets the value of the ucpTeventInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTeventInfo() {
        return ucpTeventInfo;
    }

    /**
     * Sets the value of the ucpTeventInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTeventInfo(ELonString value) {
        this.ucpTeventInfo = value;
    }

    /**
     * Gets the value of the ucpTbaseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUCPTbaseTime() {
        return ucpTbaseTime;
    }

    /**
     * Sets the value of the ucpTbaseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUCPTbaseTime(XMLGregorianCalendar value) {
        this.ucpTbaseTime = value;
    }

}
