//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized configuration type of the 'UFPTtypeTranslator'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTtypeTranslator_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="UFPTtypeTranslator_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for UFPTtypeTranslator_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTtypeTranslator_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTtranslatorRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SCPTdelayTime" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTtypeTranslator_Cfg", propOrder = {
    "ucpTtranslatorRule",
    "scpTdelayTime"
})
public class UFPTtypeTranslatorCfg
    extends FbCfg
{

    @XmlElement(name = "UCPTtranslatorRule")
    protected String ucpTtranslatorRule;
    @XmlElement(name = "SCPTdelayTime")
    protected Double scpTdelayTime;

    /**
     * Gets the value of the ucpTtranslatorRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTtranslatorRule() {
        return ucpTtranslatorRule;
    }

    /**
     * Sets the value of the ucpTtranslatorRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTtranslatorRule(String value) {
        this.ucpTtranslatorRule = value;
    }

    /**
     * Gets the value of the scpTdelayTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSCPTdelayTime() {
        return scpTdelayTime;
    }

    /**
     * Sets the value of the scpTdelayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSCPTdelayTime(Double value) {
        this.scpTdelayTime = value;
    }

}
