//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized configuration type of the 'UFPTanalogFunctionBlock'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTanalogFunctionBlock_Cfg"]"
 * 					Example:  xSelect="//Item[@xsi:type="UFPTanalogFunctionBlock_Cfg"][starts-with(UCPTname,'Net/LON/BAS/')]"
 * 			
 * 
 * <p>Java class for UFPTanalogFunctionBlock_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTanalogFunctionBlock_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTcompFunction" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="UCPTmajorityValue" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="UCPTtrueThreshold" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPToutputFunction" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="SCPTminRnge" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="SCPTmaxRnge" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTcalculationInterval" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="UCPTcalculationMatrix" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SCPTovrBehave" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString"/&gt;
 *         &lt;element name="SCPTovrValue" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_LonString" minOccurs="0"/&gt;
 *         &lt;element name="UCPTpollOnResetDelay" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTanalogFunctionBlock_Cfg", propOrder = {
    "ucpTcompFunction",
    "ucpTmajorityValue",
    "ucpTtrueThreshold",
    "ucpToutputFunction",
    "scpTminRnge",
    "scpTmaxRnge",
    "ucpTcalculationInterval",
    "ucpTcalculationMatrix",
    "scpTovrBehave",
    "scpTovrValue",
    "ucpTpollOnResetDelay"
})
public class UFPTanalogFunctionBlockCfg
    extends FbCfg
{

    @XmlElement(name = "UCPTcompFunction", required = true)
    protected ELonString ucpTcompFunction;
    @XmlElement(name = "UCPTmajorityValue")
    protected float ucpTmajorityValue;
    @XmlElement(name = "UCPTtrueThreshold")
    protected ELonString ucpTtrueThreshold;
    @XmlElement(name = "UCPToutputFunction", required = true)
    protected ELonString ucpToutputFunction;
    @XmlElement(name = "SCPTminRnge")
    protected ELonString scpTminRnge;
    @XmlElement(name = "SCPTmaxRnge")
    protected ELonString scpTmaxRnge;
    @XmlElement(name = "UCPTcalculationInterval")
    protected double ucpTcalculationInterval;
    @XmlElement(name = "UCPTcalculationMatrix")
    protected Integer ucpTcalculationMatrix;
    @XmlElement(name = "SCPTovrBehave", required = true)
    protected ELonString scpTovrBehave;
    @XmlElement(name = "SCPTovrValue")
    protected ELonString scpTovrValue;
    @XmlElement(name = "UCPTpollOnResetDelay")
    protected double ucpTpollOnResetDelay;

    /**
     * Gets the value of the ucpTcompFunction property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTcompFunction() {
        return ucpTcompFunction;
    }

    /**
     * Sets the value of the ucpTcompFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTcompFunction(ELonString value) {
        this.ucpTcompFunction = value;
    }

    /**
     * Gets the value of the ucpTmajorityValue property.
     * 
     */
    public float getUCPTmajorityValue() {
        return ucpTmajorityValue;
    }

    /**
     * Sets the value of the ucpTmajorityValue property.
     * 
     */
    public void setUCPTmajorityValue(float value) {
        this.ucpTmajorityValue = value;
    }

    /**
     * Gets the value of the ucpTtrueThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPTtrueThreshold() {
        return ucpTtrueThreshold;
    }

    /**
     * Sets the value of the ucpTtrueThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPTtrueThreshold(ELonString value) {
        this.ucpTtrueThreshold = value;
    }

    /**
     * Gets the value of the ucpToutputFunction property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getUCPToutputFunction() {
        return ucpToutputFunction;
    }

    /**
     * Sets the value of the ucpToutputFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setUCPToutputFunction(ELonString value) {
        this.ucpToutputFunction = value;
    }

    /**
     * Gets the value of the scpTminRnge property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getSCPTminRnge() {
        return scpTminRnge;
    }

    /**
     * Sets the value of the scpTminRnge property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setSCPTminRnge(ELonString value) {
        this.scpTminRnge = value;
    }

    /**
     * Gets the value of the scpTmaxRnge property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getSCPTmaxRnge() {
        return scpTmaxRnge;
    }

    /**
     * Sets the value of the scpTmaxRnge property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setSCPTmaxRnge(ELonString value) {
        this.scpTmaxRnge = value;
    }

    /**
     * Gets the value of the ucpTcalculationInterval property.
     * 
     */
    public double getUCPTcalculationInterval() {
        return ucpTcalculationInterval;
    }

    /**
     * Sets the value of the ucpTcalculationInterval property.
     * 
     */
    public void setUCPTcalculationInterval(double value) {
        this.ucpTcalculationInterval = value;
    }

    /**
     * Gets the value of the ucpTcalculationMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUCPTcalculationMatrix() {
        return ucpTcalculationMatrix;
    }

    /**
     * Sets the value of the ucpTcalculationMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUCPTcalculationMatrix(Integer value) {
        this.ucpTcalculationMatrix = value;
    }

    /**
     * Gets the value of the scpTovrBehave property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getSCPTovrBehave() {
        return scpTovrBehave;
    }

    /**
     * Sets the value of the scpTovrBehave property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setSCPTovrBehave(ELonString value) {
        this.scpTovrBehave = value;
    }

    /**
     * Gets the value of the scpTovrValue property.
     * 
     * @return
     *     possible object is
     *     {@link ELonString }
     *     
     */
    public ELonString getSCPTovrValue() {
        return scpTovrValue;
    }

    /**
     * Sets the value of the scpTovrValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELonString }
     *     
     */
    public void setSCPTovrValue(ELonString value) {
        this.scpTovrValue = value;
    }

    /**
     * Gets the value of the ucpTpollOnResetDelay property.
     * 
     */
    public double getUCPTpollOnResetDelay() {
        return ucpTpollOnResetDelay;
    }

    /**
     * Sets the value of the ucpTpollOnResetDelay property.
     * 
     */
    public void setUCPTpollOnResetDelay(double value) {
        this.ucpTpollOnResetDelay = value;
    }

}
