//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Generalized configuration type of the 'UFPTrealTimeClock'.
 * 					Example:  xSelect="//Item[@xsi:type="UFPTrealTimeClock_Cfg"]"
 * 			
 * 
 * <p>Java class for UFPTrealTimeClock_Cfg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTrealTimeClock_Cfg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}Fb_Cfg"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCPTdegLongitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="UCPTdegLatitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTrealTimeClock_Cfg", propOrder = {
    "ucpTdegLongitude",
    "ucpTdegLatitude"
})
public class UFPTrealTimeClockCfg
    extends FbCfg
{

    @XmlElement(name = "UCPTdegLongitude")
    protected double ucpTdegLongitude;
    @XmlElement(name = "UCPTdegLatitude")
    protected double ucpTdegLatitude;

    /**
     * Gets the value of the ucpTdegLongitude property.
     * 
     */
    public double getUCPTdegLongitude() {
        return ucpTdegLongitude;
    }

    /**
     * Sets the value of the ucpTdegLongitude property.
     * 
     */
    public void setUCPTdegLongitude(double value) {
        this.ucpTdegLongitude = value;
    }

    /**
     * Gets the value of the ucpTdegLatitude property.
     * 
     */
    public double getUCPTdegLatitude() {
        return ucpTdegLatitude;
    }

    /**
     * Sets the value of the ucpTdegLatitude property.
     * 
     */
    public void setUCPTdegLatitude(double value) {
        this.ucpTdegLatitude = value;
    }

}
