//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 02:58:11 PM IST 
//


package org.coi.ilon.proxyclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UFPTalarmNotifier_Input_DpRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFPTalarmNotifier_Input_DpRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_DpRef"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AlarmFlags"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UCPTlogEnable" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTinvisible" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTclearRequired" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTackRequired" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTdisabled" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                   &lt;element name="UCPTcovEnabled" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UCPTalarmGroup" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UCPTalarmPriority2" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Priority"/&gt;
 *         &lt;element name="UCPTdescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFPTalarmNotifier_Input_DpRef", propOrder = {
    "alarmFlags",
    "ucpTalarmGroup",
    "ucpTalarmPriority2",
    "ucpTdescription"
})
public class UFPTalarmNotifierInputDpRef
    extends EDpRef
{

    @XmlElement(name = "AlarmFlags", required = true)
    protected UFPTalarmNotifierInputDpRef.AlarmFlags alarmFlags;
    @XmlElement(name = "UCPTalarmGroup")
    protected int ucpTalarmGroup;
    @XmlElement(name = "UCPTalarmPriority2")
    protected int ucpTalarmPriority2;
    @XmlElement(name = "UCPTdescription", required = true)
    protected String ucpTdescription;

    /**
     * Gets the value of the alarmFlags property.
     * 
     * @return
     *     possible object is
     *     {@link UFPTalarmNotifierInputDpRef.AlarmFlags }
     *     
     */
    public UFPTalarmNotifierInputDpRef.AlarmFlags getAlarmFlags() {
        return alarmFlags;
    }

    /**
     * Sets the value of the alarmFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link UFPTalarmNotifierInputDpRef.AlarmFlags }
     *     
     */
    public void setAlarmFlags(UFPTalarmNotifierInputDpRef.AlarmFlags value) {
        this.alarmFlags = value;
    }

    /**
     * Gets the value of the ucpTalarmGroup property.
     * 
     */
    public int getUCPTalarmGroup() {
        return ucpTalarmGroup;
    }

    /**
     * Sets the value of the ucpTalarmGroup property.
     * 
     */
    public void setUCPTalarmGroup(int value) {
        this.ucpTalarmGroup = value;
    }

    /**
     * Gets the value of the ucpTalarmPriority2 property.
     * 
     */
    public int getUCPTalarmPriority2() {
        return ucpTalarmPriority2;
    }

    /**
     * Sets the value of the ucpTalarmPriority2 property.
     * 
     */
    public void setUCPTalarmPriority2(int value) {
        this.ucpTalarmPriority2 = value;
    }

    /**
     * Gets the value of the ucpTdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCPTdescription() {
        return ucpTdescription;
    }

    /**
     * Sets the value of the ucpTdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCPTdescription(String value) {
        this.ucpTdescription = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UCPTlogEnable" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTinvisible" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTclearRequired" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTackRequired" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTdisabled" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *         &lt;element name="UCPTcovEnabled" type="{http://wsdl.echelon.com/web_services_ns/ilon100/v4.0/message/}E_Flag"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ucpTlogEnable",
        "ucpTinvisible",
        "ucpTclearRequired",
        "ucpTackRequired",
        "ucpTdisabled",
        "ucpTcovEnabled"
    })
    public static class AlarmFlags {

        @XmlElement(name = "UCPTlogEnable")
        protected short ucpTlogEnable;
        @XmlElement(name = "UCPTinvisible")
        protected short ucpTinvisible;
        @XmlElement(name = "UCPTclearRequired")
        protected short ucpTclearRequired;
        @XmlElement(name = "UCPTackRequired")
        protected short ucpTackRequired;
        @XmlElement(name = "UCPTdisabled")
        protected short ucpTdisabled;
        @XmlElement(name = "UCPTcovEnabled")
        protected short ucpTcovEnabled;

        /**
         * Gets the value of the ucpTlogEnable property.
         * 
         */
        public short getUCPTlogEnable() {
            return ucpTlogEnable;
        }

        /**
         * Sets the value of the ucpTlogEnable property.
         * 
         */
        public void setUCPTlogEnable(short value) {
            this.ucpTlogEnable = value;
        }

        /**
         * Gets the value of the ucpTinvisible property.
         * 
         */
        public short getUCPTinvisible() {
            return ucpTinvisible;
        }

        /**
         * Sets the value of the ucpTinvisible property.
         * 
         */
        public void setUCPTinvisible(short value) {
            this.ucpTinvisible = value;
        }

        /**
         * Gets the value of the ucpTclearRequired property.
         * 
         */
        public short getUCPTclearRequired() {
            return ucpTclearRequired;
        }

        /**
         * Sets the value of the ucpTclearRequired property.
         * 
         */
        public void setUCPTclearRequired(short value) {
            this.ucpTclearRequired = value;
        }

        /**
         * Gets the value of the ucpTackRequired property.
         * 
         */
        public short getUCPTackRequired() {
            return ucpTackRequired;
        }

        /**
         * Sets the value of the ucpTackRequired property.
         * 
         */
        public void setUCPTackRequired(short value) {
            this.ucpTackRequired = value;
        }

        /**
         * Gets the value of the ucpTdisabled property.
         * 
         */
        public short getUCPTdisabled() {
            return ucpTdisabled;
        }

        /**
         * Sets the value of the ucpTdisabled property.
         * 
         */
        public void setUCPTdisabled(short value) {
            this.ucpTdisabled = value;
        }

        /**
         * Gets the value of the ucpTcovEnabled property.
         * 
         */
        public short getUCPTcovEnabled() {
            return ucpTcovEnabled;
        }

        /**
         * Sets the value of the ucpTcovEnabled property.
         * 
         */
        public void setUCPTcovEnabled(short value) {
            this.ucpTcovEnabled = value;
        }

    }

}
